export type AnalyticsEventName =
  | "page_view"
  | "external_resource_click"
  | "reflection_open"
  | "prayer_request_submit"
  | "prayer_copy"
  | "prayer_need_select"
  | "prayer_rhythm_build"
  | "external_prayer_resource_click"
  | "prayer_tool_click"
  | "scripture_prayer_plan_build"
  | "scripture_prayer_plan_copy"
  | "formation_path_start"
  | "formation_plan_copy"
  | "confession_examination_start"
  | "rule_of_life_start"
  | "saint_profile_open"
  | "saint_of_day_learn_more_click"
  | "saint_prayer_copy"
  | "saint_companion_finder_click"
  | "saint_companion_start"
  | "saint_companion_complete"
  | "saint_filter_apply"
  | "saint_search"
  | "saint_external_resource_click"
  | "confirmation_saint_helper_start"
  | "news_resource_click"
  | "official_news_click"
  | "spiritual_news_click"
  | "pray_the_news_copy"
  | "news_filter_apply"
  | "catechism_topic_select"
  | "catechism_study_plan_copy"
  | "catechism_resource_click"
  | "catechism_pillar_click"
  | "ocia_next_step_start"
  | "ocia_next_step_complete"
  | "ocia_parish_questions_copy"
  | "ocia_resource_click"
  | "ocia_stage_click"
  | "pope_resource_click"
  | "papal_document_click"
  | "prayer_for_pope_copy"
  | "papal_reading_method_copy"
  | "pope_related_tool_click"
  | "vatican_live_click"
  | "vatican_video_play"
  | "vatican_virtual_tour_click"
  | "vatican_resource_click"
  | "virtual_pilgrimage_print"
  | "virtual_pilgrimage_prayer_copy"
  | "tradition_classifier_use"
  | "tradition_resource_click"
  | "tradition_study_path_copy"
  | "tradition_prayer_copy"
  | "tradition_related_tool_click"
  | "family_rule_builder_start"
  | "family_rule_builder_complete"
  | "family_prayer_copy"
  | "family_virtue_select"
  | "family_resource_click"
  | "family_related_tool_click"
  | "adoration_stream_open"
  | "adoration_holy_hour_copy"
  | "adoration_prayer_copy"
  | "adoration_prayer_path_select"
  | "adoration_resource_click"
  | "adoration_related_tool_click"
  | "council_topic_finder_use"
  | "council_timeline_filter"
  | "council_resource_click"
  | "council_study_path_copy"
  | "council_related_tool_click"
  | "media_card_click"
  | "media_embed_open"
  | "media_external_open"
  | "media_filter_apply"
  | "media_share_copy"
  | "homily_card_click"
  | "homily_playlist_open"
  | "homily_video_open"
  | "homily_audio_open"
  | "homily_external_open"
  | "homily_filter_apply"
  | "homily_reflection_prompts_copy"
  | "featured_media_click"
  | "featured_media_next"
  | "featured_media_previous"
  | "media_library_cta_click"
  | "prophecy_series_playlist_click"
  | "prophecy_series_subscribe_click"
  | "prophecy_series_episode_click"
  | "prophecy_series_prayer_copy"
  | "prophecy_series_share_click"
  | "angels_prayer_copy"
  | "angels_study_path_copy"
  | "angels_resource_click"
  | "angels_related_tool_click"
  | "saint_of_day_external_click"
  | "saint_of_day_prayer_copy"
  | "saint_of_day_date_select"
  | "saint_of_day_related_click"
  | "sacramental_finder_use"
  | "sacramental_prayer_copy"
  | "sacramental_purchase_link_click"
  | "sacramental_resource_click"
  | "sacramental_related_tool_click"
  | "relic_prayer_copy"
  | "relic_visit_tool_use"
  | "relic_resource_click"
  | "relic_related_tool_click"
  | "bible_resource_click"
  | "bible_translation_finder_use"
  | "bible_reading_plan_copy"
  | "bible_word_journal_copy"
  | "bible_related_tool_click"
  | "daily_examen_start"
  | "daily_examen_guide_copy"
  | "quick_examen_copy"
  | "examen_prayer_copy"
  | "examen_journal_prompt_copy"
  | "examen_related_tool_click"
  | "rosary_prayer_room_click"
  | "rosary_mystery_group_click"
  | "rosary_mystery_detail_open"
  | "rosary_mystery_prayer_copy"
  | "rosary_decade_guide_copy"
  | "body_soul_spirit_prayer_copy"
  | "interior_temple_checkup_start"
  | "interior_temple_checkup_complete"
  | "interior_temple_reflection_copy"
  | "body_soul_spirit_related_click"
  | "sin_topic_open"
  | "temptation_plan_copy"
  | "temptation_plan_print"
  | "predominant_fault_tool_copy"
  | "near_occasion_audit_copy"
  | "freedom_plan_copy"
  | "confession_guide_click"
  | "epiphany_prayer_copy"
  | "house_blessing_plan_copy"
  | "house_blessing_plan_print"
  | "epiphany_resource_click"
  | "grace_topic_open"
  | "grace_prayer_copy"
  | "grace_reflection_copy"
  | "grace_plan_print"
  | "grace_related_link_click"
  | "detachment_prayer_copy"
  | "detachment_plan_copy"
  | "detachment_plan_print"
  | "detachment_related_link_click"
  | "penitential_psalms_read_psalm_click"
  | "penitential_psalms_copy_prayer"
  | "penitential_psalms_copy_plan"
  | "penitential_psalms_print_plan"
  | "penitential_psalms_confession_click"
  | "eschatology_topic_open"
  | "eschatology_prayer_copy"
  | "eschatology_related_link_click"
  | "prophecy_series_from_eschatology_click"
  | "catholic_burial_topic_open"
  | "catholic_burial_prayer_copy"
  | "funeral_checklist_copy"
  | "funeral_checklist_print"
  | "funeral_planning_notes_copy"
  | "funeral_planning_notes_print"
  | "catholic_burial_reference_click"
  | "catholic_life_section_click"
  | "catholic_life_track_click"
  | "catholic_life_related_link_click"
  | "catholic_life_weekly_rhythm_click"
  | "lenten_plan_copy"
  | "lenten_plan_print"
  | "lenten_prayer_copy"
  | "stations_guide_open"
  | "sacramental_emergency_card_click"
  | "sacramental_emergency_anchor_click"
  | "sacramental_emergency_prayer_copy"
  | "sacramental_emergency_checklist_copy"
  | "sacramental_emergency_checklist_print"
  | "sacramental_emergency_related_link_click";

export type AnalyticsParams = Record<string, string | number | boolean | null | undefined>;

declare global {
  interface Window {
    dataLayer?: unknown[];
    gtag?: (
      command: "config" | "event",
      targetIdOrEventName: string,
      params?: Record<string, string | number | boolean>,
    ) => void;
  }
}

function cleanParams(params: AnalyticsParams = {}) {
  return Object.fromEntries(
    Object.entries(params).filter(
      (entry): entry is [string, string | number | boolean] =>
        entry[1] !== undefined && entry[1] !== null,
    ),
  );
}

export function trackEvent(eventName: AnalyticsEventName, params: AnalyticsParams = {}) {
  if (typeof window === "undefined" || typeof window.gtag !== "function") return;
  window.gtag("event", eventName, cleanParams(params));
}

export function trackPageView(pagePath: string, pageTitle?: string) {
  trackEvent("page_view", {
    page_path: pagePath,
    page_title: pageTitle,
  });
}
