const config = {
  content: [
    "./src/app/**/*.{ts,tsx,mdx}",
    "./src/components/**/*.{ts,tsx,mdx}",
    "./src/content/**/*.{ts,tsx,mdx}",
    "./src/data/**/*.{ts,tsx}",
    "./src/lib/**/*.{ts,tsx}",
    "./docs/**/*.{md,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        ivory: "var(--ivory)",
        parchment: "var(--parchment)",
        "parchment-deep": "var(--parchment-deep)",
        navy: "var(--navy)",
        "navy-soft": "var(--navy-soft)",
        gold: "var(--gold)",
        "gold-soft": "var(--gold-soft)",
        "gold-muted": "var(--gold-muted)",
        burgundy: "var(--burgundy)",
        "burgundy-soft": "var(--burgundy-soft)",
        stone: "var(--stone)",
        "stone-soft": "var(--stone-soft)",
        muted: "var(--muted)",
        success: "var(--success)",
        advent: "var(--season-advent)",
        christmas: "var(--season-christmas)",
        lent: "var(--season-lent)",
        easter: "var(--season-easter)",
        pentecost: "var(--season-pentecost)",
        ordinary: "var(--season-ordinary)",
        marian: "var(--season-marian)",
      },
      fontFamily: {
        sans: ["var(--font-geist-sans)", "Arial", "Helvetica", "sans-serif"],
        display: ["var(--font-cormorant)", "Cormorant Garamond", "Times New Roman", "serif"],
        serif: ["var(--font-cormorant)", "Cormorant Garamond", "Times New Roman", "serif"],
        mono: ["var(--font-geist-mono)", "Consolas", "monospace"],
      },
      spacing: {
        "section-xs": "var(--space-section-xs)",
        "section-sm": "var(--space-section-sm)",
        section: "var(--space-section)",
        "section-lg": "var(--space-section-lg)",
        gutter: "var(--space-gutter)",
      },
      borderRadius: {
        none: "0",
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "999px",
      },
      boxShadow: {
        hairline: "var(--shadow-hairline)",
        oratory: "var(--shadow-oratory)",
        lifted: "var(--shadow-lifted)",
        inset: "var(--shadow-inset)",
      },
      maxWidth: {
        reading: "72ch",
        prayer: "62rem",
        shell: "80rem",
      },
      fontSize: {
        prayer: ["clamp(1.35rem, 2vw, 1.8rem)", { lineHeight: "1.85" }],
        "display-xl": ["clamp(3.25rem, 8vw, 6.75rem)", { lineHeight: "0.92" }],
      },
    },
  },
  plugins: [],
} as const;

export default config;
