export type TimeCertainty = "scriptural" | "traditional" | "approximate" | "untimed";
export type SacredMood = "daylight" | "candlelight" | "indigo" | "stone" | "calvary" | "silence" | "dawn";

export type SacredMoment = {
  id: string;
  sequence: number;
  liturgicalDay: string;
  displayTime?: string;
  location?: string;
  event?: string;
  timeRange?: string;
  timelineLabel?: string;
  timeCertainty: TimeCertainty;
  title: string;
  subtitle: string;
  scriptureReference: string;
  scripturePassages: { reference: string; verses: { number: number; text: string }[]; sourceUrl: string }[];
  theme: string;
  virtue: string;
  meditation: string[];
  reflectionQuestions: string[];
  responsePrayer: string;
  openingPrayer?: string;
  virtueDescription?: string;
  virtuePrayer?: string;
  imageDescription: string;
  imageAlt: string;
  imageSrc?: string;
  imageFocalPoint?: string;
  visualMood: SacredMood;
  optionalFeature?: "remain" | "watch" | "calvary" | "death" | "silence" | "emmaus";
  hour?: number;
  minute?: number;
  dayOffset?: number;
};
