export type NavigationItem = {
  label: string;
  href: string;
  description?: string;
  external?: boolean;
};

export type NavigationGroup = {
  title: string;
  children: NavigationItem[];
};

export { legacyRedirects, redirectMap, type RedirectRule } from "@/data/redirects";

export type NavigationSection = {
  id: string;
  label: string;
  description: string;
  groups: NavigationGroup[];
};

const navigationSections: NavigationSection[] = [
  {
    id: "pray",
    label: "Pray",
    description: "Begin in prayer and keep a peaceful Catholic rhythm throughout the day.",
    groups: [
      {
        title: "Prayer Through the Day",
        children: [
          { label: "Morning Prayer", href: "/morning-prayer" },
          { label: "Midday Prayer", href: "/prayers/angelus" },
          { label: "3 pm Prayer", href: "/divine-mercy/three-pm-prayer" },
          { label: "Daily Examen", href: "/daily-examen/nightly" },
          { label: "Night Prayer", href: "/night-prayer" },
        ],
      },
      {
        title: "Devotions",
        children: [
          { label: "Pray the Rosary", href: "/rosary/visual-meditation" },
          { label: "Pray a Litany", href: "/prayers/litanies" },
          { label: "Divine Mercy Chaplet", href: "/divine-mercy/chaplet" },
          { label: "The Way of the Cross", href: "/way-of-cross" },
        ],
      },
    ],
  },
  {
    id: "mass-adoration",
    label: "Mass & Adoration",
    description: "Enter more deeply into the Mass, Eucharistic Adoration, and preparation of heart.",
    groups: [
      {
        title: "Mass and the Word",
        children: [
          { label: "Daily Scripture Reflections", href: "/reflections/mass-readings" },
          { label: "The Holy Mass", href: "/mass" },
        ],
      },
      {
        title: "Eucharistic Adoration",
        children: [
          { label: "Adoration Meditation", href: "/adoration/companion" },
          { label: "Holy Hour Meditation", href: "/adoration/companion?mode=holy-hour" },
        ],
      },
      {
        title: "Retreat and Preparation",
        children: [
          { label: "The Sacred Hours", href: "/holy-week" },
          { label: "Three-Day Fasting Retreat", href: "/fasting-retreat" },
          { label: "Guided Examination of Conscience", href: "/confession/examination-companion" },
        ],
      },
    ],
  },
  {
    id: "learn",
    label: "Learn",
    description: "Grow in Scripture, Tradition, the Church Fathers, and the Catechism.",
    groups: [
      {
        title: "Foundations of the Faith",
        children: [
          { label: "The Bible and Sacred Scripture", href: "/bible" },
          { label: "The Life of Jesus", href: "/life-of-jesus" },
          { label: "Sacred Tradition", href: "/tradition" },
          { label: "Church Fathers", href: "/church-fathers" },
          { label: "Catechism of the Catholic Church", href: "/catechism" },
          { label: "Media", href: "/media" },
        ],
      },
    ],
  },
  {
    id: "external-resources",
    label: "External Resources",
    description: "Trusted resources that open outside Daily Oratory.",
    groups: [
      {
        title: "Read and Discover",
        children: [
          { label: "Today's Daily Readings", href: "https://bible.usccb.org/daily-bible-reading", external: true },
          { label: "Today's Saint", href: "https://www.franciscanmedia.org/saint-of-the-day/", external: true },
          { label: "Eucharistic Miracles", href: "https://www.miracolieucaristici.org/en/liste/list.html", external: true },
        ],
      },
      {
        title: "Spiritual Companions",
        children: [
          { label: "Heavenbound", href: "https://chatgpt.com/g/g-68858af32c348191bd1d17ae4c8bda79-heavenbound", external: true },
          { label: "NotebookLM Library", href: "https://notebook.google.com/notebook/24faf824-e6ff-4a7c-b7f8-fd1d51ee32f0?authuser=1", external: true },
        ],
      },
      {
        title: "Find a Mass",
        children: [
          { label: "Catholic Mass Times", href: "https://catholicmasstimes.com/", external: true },
          { label: "MassTimes.org", href: "https://masstimes.org/", external: true },
        ],
      },
    ],
  },
];

export const siteNavigation = navigationSections;

export const primaryNavigation = Array.from(
  new Map(
    navigationSections
      .flatMap((section) => section.groups.flatMap((group) => group.children))
      .filter((item) => !item.external)
      .map((item) => [item.href, { label: item.label, href: item.href }]),
  ).values(),
);

export const desktopMegaMenu = siteNavigation;

export const mobileDrawerNavigation = siteNavigation;

export const footerNavigationGroups = [
  {
    title: "Begin",
    links: [
      { label: "Begin in prayer", href: "/morning-prayer" },
      { label: "Confession Guide", href: "/confession" },
    ],
  },
  {
    title: "Grow",
    links: [
      { label: "Mass Readings Reflections", href: "/reflections/mass-readings" },
      { label: "Find a saint companion", href: "/saints" },
    ],
  },
] as const;

export const breadcrumbPatterns = [
  { pattern: "/", label: "Home" },
  { pattern: "/what-should-i-do", label: "What Should I Do?" },
  { pattern: "/catholic-life", label: "Catholic Life Roadmap" },
  { pattern: "/catholic-answers", label: "Catholic Q&A" },
  { pattern: "/pray", label: "Pray" },
  { pattern: "/begin-in-prayer", label: "Morning Prayers" },
  { pattern: "/prayers", label: "Prayer Library" },
  { pattern: "/prayers/litanies", label: "Catholic Litanies" },
  { pattern: "/daily-examen", label: "Daily Examen" },
  { pattern: "/liturgy-of-the-hours", label: "Liturgy of the Hours" },
  { pattern: "/divine-office", label: "Divine Office" },
  { pattern: "/prayer/liturgy-of-the-hours", label: "Liturgy of the Hours" },
  { pattern: "/rosary", label: "Rosary" },
  { pattern: "/rosary/joyful-mysteries", label: "Joyful Mysteries" },
  { pattern: "/rosary/sorrowful-mysteries", label: "Sorrowful Mysteries" },
  { pattern: "/rosary/glorious-mysteries", label: "Glorious Mysteries" },
  { pattern: "/rosary/luminous-mysteries", label: "Luminous Mysteries" },
  { pattern: "/rosary/latin-rosary", label: "Latin Rosary" },
  { pattern: "/divine-mercy", label: "Divine Mercy" },
  { pattern: "/devotions", label: "Devotions" },
  { pattern: "/devotions/[slug]", label: "Devotion" },
  { pattern: "/library/scripture-prayer", label: "Scripture Prayer" },
  { pattern: "/mass", label: "The Holy Mass" },
  { pattern: "/holy-mass", label: "The Holy Mass" },
  { pattern: "/library/mass", label: "The Holy Mass" },
  { pattern: "/library/holy-mass", label: "The Holy Mass" },
  { pattern: "/way-of-cross", label: "Way of the Cross" },
  { pattern: "/eucharistic-miracles", label: "Eucharistic Miracles" },
  { pattern: "/eucharistic-stations", label: "Stations of the Eucharist" },
  { pattern: "/resurrection-stations", label: "Stations of the Resurrection" },
  { pattern: "/reflect", label: "Reflect" },
  { pattern: "/reflections", label: "Mass Readings Reflections" },
  { pattern: "/reflections/mass-readings", label: "Mass Readings Reflections" },
  { pattern: "/reflections/mass-readings/archive", label: "Archive" },
  { pattern: "/reflections/mass-readings/calendar", label: "Calendar" },
  { pattern: "/reflections/mass-readings/upcoming", label: "Upcoming" },
  { pattern: "/reflections/mass-readings/[slug]", label: "Mass Reading Reflection" },
  { pattern: "/reflections/daily", label: "Daily Mass Reflections" },
  { pattern: "/reflections/sunday", label: "Sunday Mass Reflections" },
  { pattern: "/reflections/[slug]", label: "Reflection" },
  { pattern: "/learn", label: "Learn" },
  { pattern: "/bible", label: "Bible" },
  { pattern: "/life-of-jesus", label: "Life of Jesus" },
  { pattern: "/body-soul-spirit", label: "Body, Soul, and Spirit" },
  { pattern: "/sin-and-temptation", label: "Sin & Temptation" },
  { pattern: "/spiritual-warfare", label: "Spiritual Warfare" },
  { pattern: "/sin-and-temptation/venial-and-mortal-sin", label: "Venial and Mortal Sin" },
  { pattern: "/sin-and-temptation/habitual-sin", label: "Habitual Sin" },
  { pattern: "/sin-and-temptation/predominant-fault", label: "Predominant Fault" },
  { pattern: "/sin-and-temptation/resisting-temptation", label: "Resisting Temptation" },
  { pattern: "/sin-and-temptation/near-occasions-of-sin", label: "Near Occasions of Sin" },
  { pattern: "/sin-and-temptation/examination-and-confession", label: "Examination and Confession" },
  { pattern: "/sin-and-temptation/virtue-and-healing", label: "Virtue and Healing" },
  { pattern: "/angels", label: "Angels and the Invisible World" },
  { pattern: "/sacramentals", label: "Sacramentals" },
  { pattern: "/relics", label: "Relics" },
  { pattern: "/media", label: "Media Library" },
  { pattern: "/prophecy-series", label: "Prophecy Series" },
  { pattern: "/media/prophecy-series", label: "Prophecy Series" },
  { pattern: "/media/[slug]", label: "Media Item" },
  { pattern: "/homilies", label: "Homilies" },
  { pattern: "/news", label: "Catholic News" },
  { pattern: "/explore", label: "Explore the Catholic Faith" },
  { pattern: "/explore/first-time-at-mass", label: "First Time at Mass" },
  { pattern: "/explore/questions", label: "Common Questions" },
  { pattern: "/returning", label: "Returning Catholics" },
  { pattern: "/glossary", label: "Glossary" },
  { pattern: "/catechism", label: "Catechism" },
  { pattern: "/ocia", label: "Becoming Catholic" },
  { pattern: "/tradition", label: "Sacred Tradition" },
  { pattern: "/family", label: "The Domestic Church" },
  { pattern: "/pope", label: "The Pope" },
  { pattern: "/vatican", label: "The Vatican" },
  { pattern: "/formation", label: "Formation" },
  { pattern: "/formation/grace", label: "Grace" },
  { pattern: "/formation/grace/sanctifying-grace", label: "Sanctifying Grace" },
  { pattern: "/formation/grace/actual-grace", label: "Actual Grace" },
  { pattern: "/formation/grace/sacramental-grace", label: "Sacramental Grace" },
  { pattern: "/formation/grace/charisms", label: "Charisms" },
  { pattern: "/formation/grace/cooperating-with-grace", label: "Cooperating with Grace" },
  { pattern: "/church-fathers", label: "Church Fathers" },
  { pattern: "/indulgences", label: "Indulgences" },
  { pattern: "/tools", label: "Tools" },
  { pattern: "/tools/heavenbound", label: "Heavenbound Companion" },
  { pattern: "/liturgical-year", label: "Liturgical Year" },
  { pattern: "/today", label: "Today in the Church" },
  { pattern: "/dashboard", label: "Dashboard" },
  { pattern: "/liturgical-living", label: "Liturgical Living" },
  { pattern: "/liturgical-living/lent", label: "Lent" },
  { pattern: "/liturgical-living/calendar", label: "Calendar" },
  { pattern: "/liturgical-living/seasons", label: "Seasons" },
  { pattern: "/liturgical-living/advent", label: "Advent" },
  { pattern: "/liturgical-living/advent/o-antiphons", label: "O Antiphons" },
  { pattern: "/liturgical-living/christmas", label: "Christmas" },
  { pattern: "/liturgical-living/christmas/epiphany", label: "Epiphany" },
  { pattern: "/liturgical-living/christmas/epiphany/house-blessing", label: "House Blessing" },
  { pattern: "/liturgical-living/holy-days", label: "Holy Days" },
  { pattern: "/liturgical-living/family", label: "Family" },
  { pattern: "/liturgical-living/settings", label: "Settings" },
  { pattern: "/rule-of-life", label: "Rule of Life" },
  { pattern: "/rule-of-life/builder", label: "Builder" },
  { pattern: "/rule-of-life/my-rule", label: "My Rule" },
  { pattern: "/rule-of-life/templates", label: "Templates" },
  { pattern: "/rule-of-life/examen", label: "Daily Examen" },
  { pattern: "/rule-of-life/print", label: "Print" },
  { pattern: "/pathways", label: "Pathways" },
  { pattern: "/pathways/start", label: "Start" },
  { pattern: "/pathways/my-pathways", label: "My Pathways" },
  { pattern: "/pathways/recommended", label: "Recommended" },
  { pattern: "/pathways/settings", label: "Settings" },
  { pattern: "/pathways/[slug]", label: "Pathway" },
  { pattern: "/pathways/[slug]/steps/[stepSlug]", label: "Pathway Step" },
  { pattern: "/sacraments", label: "Sacraments" },
  { pattern: "/sacraments/baptism", label: "Baptism" },
  { pattern: "/sacraments/confirmation", label: "Confirmation" },
  { pattern: "/sacraments/eucharist", label: "Eucharist" },
  { pattern: "/sacraments/eucharist/mass", label: "The Holy Mass" },
  { pattern: "/sacraments/reconciliation", label: "Reconciliation" },
  { pattern: "/sacraments/anointing", label: "Anointing of the Sick" },
  { pattern: "/sacraments/matrimony", label: "Matrimony" },
  { pattern: "/sacraments/marriage", label: "Marriage" },
  { pattern: "/sacraments/holy-orders", label: "Holy Orders" },
  { pattern: "/sacraments/ocia", label: "OCIA" },
  { pattern: "/sacraments/sponsor-godparent", label: "Sponsor and Godparent Guide" },
  { pattern: "/sacraments/first-communion", label: "First Communion" },
  { pattern: "/sacraments/companion", label: "Companion" },
  { pattern: "/sacraments/prepare", label: "Prepare" },
  { pattern: "/sacraments/my-preparation", label: "My Preparation" },
  { pattern: "/sacraments/print", label: "Print" },
  { pattern: "/sacraments/[slug]", label: "Sacrament Companion" },
  { pattern: "/confession", label: "Confession Guide" },
  { pattern: "/confession/examination", label: "Guided Examination" },
  { pattern: "/confession/examination/start", label: "Start" },
  { pattern: "/confession/examination/ten-commandments", label: "Ten Commandments" },
  { pattern: "/confession/examination/beatitudes", label: "Beatitudes" },
  { pattern: "/confession/examination/state-of-life", label: "State of Life" },
  { pattern: "/confession/examination/virtues", label: "Virtues" },
  { pattern: "/confession/examination/review", label: "Review" },
  { pattern: "/confession/how-to-go", label: "How to Go to Confession" },
  { pattern: "/confession/sins", label: "Sins" },
  { pattern: "/confession/habitual-sin", label: "Habitual Sin" },
  { pattern: "/confession/resisting-temptation", label: "Resisting Temptation" },
  { pattern: "/confession/predominant-fault", label: "Predominant Fault" },
  { pattern: "/confession/prayers", label: "Confession Prayers" },
  { pattern: "/catholic-life", label: "Catholic Life Roadmap" },
  { pattern: "/sacramental-emergency", label: "Sacramental Emergency Guide" },
  { pattern: "/indulgences", label: "Indulgences" },
  { pattern: "/indulgences/detachment-from-sin", label: "Complete Detachment from Sin" },
  { pattern: "/formation/catholic-burial", label: "Catholic Burial" },
  { pattern: "/formation/catholic-burial/cremation", label: "Cremation" },
  { pattern: "/formation/catholic-burial/funeral-rites", label: "Funeral Rites" },
  { pattern: "/formation/catholic-burial/prayers-for-the-dead", label: "Prayers for the Dead" },
  { pattern: "/formation/catholic-burial/planning-a-catholic-funeral", label: "Planning a Catholic Funeral" },
  { pattern: "/virtue-tracker", label: "Virtue Tracker" },
  { pattern: "/virtue-tracker/dashboard", label: "Dashboard" },
  { pattern: "/virtue-tracker/check-in", label: "Check-in" },
  { pattern: "/virtue-tracker/virtues", label: "Virtues" },
  { pattern: "/virtue-tracker/vices", label: "Vices" },
  { pattern: "/virtue-tracker/patterns", label: "Patterns" },
  { pattern: "/virtue-tracker/confession-prep", label: "Confession Prep" },
  { pattern: "/virtue-tracker/settings", label: "Settings" },
  { pattern: "/saints", label: "Saints" },
  { pattern: "/saints/finder", label: "Finder" },
  { pattern: "/saints/calendar", label: "Saint Calendar" },
  { pattern: "/saints/patron-saints", label: "Patron Saints" },
  { pattern: "/saints/virtues", label: "Saints by Virtue" },
  { pattern: "/saints/reading-plan", label: "Saint Reading Plan" },
  { pattern: "/saints/confirmation", label: "Confirmation Saint Helper" },
  { pattern: "/saints/saint-of-the-day", label: "Saint of the Day" },
  { pattern: "/saints/companions", label: "Companions" },
  { pattern: "/saints/patronage", label: "Patronage" },
  { pattern: "/saints/settings", label: "Settings" },
  { pattern: "/saints/[slug]", label: "Saint Profile" },
  { pattern: "/ask-for-prayer", label: "Ask for Prayer" },
  { pattern: "/community/events", label: "Events" },
  { pattern: "/community/events/[slug]", label: "Event" },
  { pattern: "/community/local-faith-groups", label: "Local Faith Groups" },
  { pattern: "/community/group-discussion-topics", label: "Group Discussion Topics" },
  { pattern: "/community/contact", label: "Contact" },
  { pattern: "/adoration", label: "Adoration" },
  { pattern: "/adoration/live", label: "Live Adoration" },
  { pattern: "/adoration/[slug]", label: "Adoration Chapel" },
  { pattern: "/adoration/prayers", label: "Adoration Prayers" },
  { pattern: "/adoration/submit-stream", label: "Submit Stream" },
  { pattern: "/prayer-intentions", label: "Prayer Intentions" },
  { pattern: "/prayer-intentions/submit", label: "Submit" },
  { pattern: "/prayer-intentions/wall", label: "Prayer Intentions" },
  { pattern: "/prayer-intentions/urgent", label: "Urgent" },
  { pattern: "/prayer-intentions/thanksgivings", label: "Thanksgivings" },
  { pattern: "/prayer-intentions/guidelines", label: "Guidelines" },
  { pattern: "/prayer-intentions/[slug]", label: "Prayer Intention" },
  { pattern: "/library", label: "Library" },
  { pattern: "/library/[slug]", label: "Resource" },
  { pattern: "/about", label: "About" },
  { pattern: "/mission", label: "Mission" },
  { pattern: "/contact", label: "Contact" },
] as const;

export const urlStructure = [
  { path: "/", purpose: "Home and primary starting points" },
  { path: "/pray", purpose: "Prayer, Rosary, Adoration, prayer rooms, rule of life, confession" },
  { path: "/rosary", purpose: "Holy Rosary overview, how to pray, mystery selector, and day-of-week recommendation" },
  { path: "/rosary/joyful-mysteries", purpose: "Joyful Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/sorrowful-mysteries", purpose: "Sorrowful Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/glorious-mysteries", purpose: "Glorious Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/luminous-mysteries", purpose: "Luminous Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/latin-rosary", purpose: "Latin Rosary guide with English cues and pronunciation help" },
  { path: "/divine-mercy", purpose: "Divine Mercy Chaplet quiet room with prayers and stream selector" },
  { path: "/devotions", purpose: "Catholic Devotions Library with featured devotions, needs-based recommendations, filters, and guidance" },
  { path: "/devotions/[slug]", purpose: "Catholic devotion detail page with pastoral guidance, trusted links, related tools, and source notes" },
  { path: "/way-of-cross", purpose: "Way of the Cross quiet room with St. Alphonsus Liguori station prayers and video meditation" },
  { path: "/eucharistic-miracles", purpose: "Eucharistic Miracles launch page linking to the external miracle catalog" },
  { path: "/eucharistic-stations", purpose: "Fourteen Stations of the Eucharist quiet room with prayers and video meditation" },
  { path: "/resurrection-stations", purpose: "Fourteen Stations of the Resurrection quiet room with video meditation and linked prayer booklet" },
  { path: "/reflect", purpose: "Daily and Sunday reflections, conscience, virtue and vice review" },
  { path: "/reflections", purpose: "Legacy alias that redirects to Mass Readings Reflections." },
  { path: "/reflections/mass-readings", purpose: "Mass Readings Reflections landing with today's reflection, Sunday Mass reflections, upcoming, archive, search, and filters" },
  { path: "/reflections/mass-readings/archive", purpose: "Archive of published Mass reading reflections grouped by month" },
  { path: "/reflections/mass-readings/calendar", purpose: "Calendar browsing for published and scheduled Mass reading reflections" },
  { path: "/reflections/mass-readings/upcoming", purpose: "Upcoming scheduled daily Mass, Sunday Mass, feast day, and solemnity reflections" },
  { path: "/reflections/mass-readings/[slug]", purpose: "Mass reading reflection detail with reading references, theology, prayer, and practical application" },
  { path: "/reflections/daily", purpose: "Legacy daily Mass reflections alias redirecting to filtered Mass Readings Reflections" },
  { path: "/reflections/sunday", purpose: "Legacy Sunday Mass reflections alias redirecting to filtered Mass Readings Reflections" },
  { path: "/reflections/[slug]", purpose: "Legacy reflection detail alias redirecting to canonical Mass Readings Reflection detail" },
  { path: "/learn", purpose: "Sacraments, saints, devotions, Scripture, Mass, formation" },
  { path: "/bible", purpose: "Catholic guide to Sacred Scripture, Bible translations, daily readings, and Scripture prayer" },
  { path: "/life-of-jesus", purpose: "A Pilgrim's Path through the life of Jesus with exact Scripture references and in-page Douay–Rheims reading" },
  { path: "/body-soul-spirit", purpose: "Catholic formation guide to the human person, grace, sin, Confession, Eucharist, and the soul as an interior temple of God" },
  { path: "/sin-and-temptation", purpose: "Catholic guide to sin, temptation, repentance, Confession, virtue, healing, and ongoing conversion" },
  { path: "/sin-and-temptation/venial-and-mortal-sin", purpose: "Pastoral guide to the distinction between venial and mortal sin" },
  { path: "/sin-and-temptation/habitual-sin", purpose: "Guide to repeated sin patterns, triggers, safeguards, and perseverance in grace" },
  { path: "/sin-and-temptation/predominant-fault", purpose: "Self-knowledge guide for identifying a recurring root weakness and contrary virtue" },
  { path: "/sin-and-temptation/resisting-temptation", purpose: "Practical Catholic guide and emergency plan for resisting temptation" },
  { path: "/sin-and-temptation/near-occasions-of-sin", purpose: "Guide to identifying and avoiding near occasions of sin" },
  { path: "/sin-and-temptation/examination-and-confession", purpose: "Guide to conscience, contrition, amendment, and Confession preparation" },
  { path: "/sin-and-temptation/virtue-and-healing", purpose: "Guide to opposite virtues, healing, sacramental life, and spiritual freedom" },
  { path: "/news", purpose: "Catholic news hub with official Church sources, trusted media links, and prayerful discernment" },
  { path: "/catechism", purpose: "Beginner-friendly Catechism guide with four pillars, topic finder, reading plan, and official Vatican and USCCB resources" },
  { path: "/angels", purpose: "Catholic guide to angels, guardian angels, archangels, heavenly worship, spiritual protection, and the invisible world" },
  { path: "/relics", purpose: "Catholic guide to relics, relic classes, reliquaries, veneration, pilgrimage, and the communion of saints" },
  { path: "/daily-examen", purpose: "Daily Examen guide for gratitude, mercy, review, trust, and peaceful night prayer" },
  { path: "/night-prayer", purpose: "Guided Catholic prayer for protection during sleep with the Our Father and prayer to Saint Michael" },
  { path: "/ocia", purpose: "Welcoming OCIA guide for adults exploring Catholicism, preparing for initiation, or seeking full communion" },
  { path: "/tradition", purpose: "Beginner-friendly guide to Sacred Tradition, Scripture, the Magisterium, apostolic succession, Church Fathers, and the deposit of faith" },
  { path: "/family", purpose: "Beginner-friendly guide to the domestic church, family prayer, family virtue, sacramental life, and Catholic formation in the home" },
  { path: "/pope", purpose: "Beginner-friendly guide to the Pope, papacy, papal documents, papal teaching, and prayer for the Holy Father" },
  { path: "/vatican", purpose: "Beginner-friendly guide to Vatican City, Saint Peter's Basilica, Vatican live broadcasts, sacred art, history, and virtual pilgrimage" },
  { path: "/mass", purpose: "The Holy Mass guide with liturgical walkthrough, sacred spaces, Real Presence, and prayerful participation" },
  { path: "/catholic-life", purpose: "Master start-here roadmap linking prayer, Mass, Confession, Scripture, grace, family faith, formation, and Catholic hope" },
  { path: "/sacramental-emergency", purpose: "Calm practical guide for urgent Catholic sacramental situations including danger of death, Anointing, Confession, Viaticum, and prayer" },
  { path: "/prophecy-series", purpose: "Daily Oratory Prophecy Series page with playlist, premiere schedule, episode tracker, prayer, and discernment guidance" },
  { path: "/formation/grace", purpose: "Catholic guide to grace, sanctifying grace, actual grace, sacramental grace, charisms, and cooperation with grace" },
  { path: "/formation/grace/sanctifying-grace", purpose: "Guide to sanctifying grace, holiness, Baptism, Eucharist, sin, and Confession" },
  { path: "/formation/grace/actual-grace", purpose: "Guide to God’s help in specific moments of temptation, repentance, prayer, and service" },
  { path: "/formation/grace/sacramental-grace", purpose: "Guide to sacramental grace and the grace proper to each sacrament" },
  { path: "/formation/grace/charisms", purpose: "Guide to charisms, special graces, discernment, humility, and service in the Church" },
  { path: "/formation/grace/cooperating-with-grace", purpose: "Guide to responding to grace through prayer, sacraments, virtue, and charity" },
  { path: "/formation/catholic-burial", purpose: "Catholic guide to burial, cremation, funeral rites, prayer for the dead, and funeral planning with hope in the resurrection" },
  { path: "/formation/catholic-burial/cremation", purpose: "Catholic cremation guide with reverent care for remains, interment guidance, and pastoral next steps" },
  { path: "/formation/catholic-burial/funeral-rites", purpose: "Guide to the Vigil, Funeral Mass, Rite of Committal, and family participation in Catholic funeral rites" },
  { path: "/formation/catholic-burial/prayers-for-the-dead", purpose: "Prayer page for deceased loved ones, souls in Purgatory, cemetery visits, anniversaries, and remembrance" },
  { path: "/formation/catholic-burial/planning-a-catholic-funeral", purpose: "Practical Catholic funeral planning guide with checklist and local-only planning notes tool" },
  { path: "/church-fathers", purpose: "Beginner-friendly Church Fathers guide, topic browser, reading plan, and trusted external research links" },
  { path: "/tools/heavenbound", purpose: "Launch portal for the external Heavenbound GPT spiritual companion" },
  { path: "/today", purpose: "Today in the Church dashboard" },
  { path: "/dashboard", purpose: "Alias for the liturgical living dashboard" },
  { path: "/liturgical-living", purpose: "Today in the Church, calendar, seasons, holy days, family practices" },
  { path: "/liturgical-living/calendar", purpose: "Liturgical month view with daily records" },
  { path: "/liturgical-living/seasons", purpose: "Season records, colors, focus, and practices" },
  { path: "/liturgical-living/advent", purpose: "Advent guide with hopeful preparation, confession, Scripture, and O Antiphon prayer" },
  { path: "/liturgical-living/advent/o-antiphons", purpose: "Guide to the O Antiphons prayed from December 17 to 23 as final preparation for Christmas" },
  { path: "/liturgical-living/christmas", purpose: "Christmas season guide and Advent-to-Christmas transition through the O Antiphons" },
  { path: "/liturgical-living/christmas/epiphany", purpose: "Epiphany guide for following the Magi, prayer, house blessing, and Christmas mission" },
  { path: "/liturgical-living/christmas/epiphany/house-blessing", purpose: "Family Epiphany home blessing guide and local-only printable planning tool" },
  { path: "/liturgical-living/holy-days", purpose: "Holy days and solemnities with local observance notes" },
  { path: "/liturgical-living/family", purpose: "Family prayer ideas and domestic Church practices" },
  { path: "/liturgical-living/settings", purpose: "Local calendar settings and Google Sheets schema" },
  { path: "/rule-of-life", purpose: "Daily Rule of Life overview" },
  { path: "/rule-of-life/builder", purpose: "LocalStorage rule of life builder" },
  { path: "/rule-of-life/my-rule", purpose: "Saved local rule display and export" },
  { path: "/rule-of-life/templates", purpose: "Rule of life templates" },
  { path: "/rule-of-life/examen", purpose: "Daily Examen guide" },
  { path: "/rule-of-life/print", purpose: "Printable rule of life view" },
  { path: "/pathways", purpose: "Spiritual Growth Pathways overview" },
  { path: "/pathways/start", purpose: "Choose a guided formation starting point" },
  { path: "/pathways/my-pathways", purpose: "LocalStorage pathway progress" },
  { path: "/pathways/recommended", purpose: "Local settings-based pathway recommendations" },
  { path: "/pathways/settings", purpose: "Local pathway recommendation settings" },
  { path: "/pathways/[slug]", purpose: "Spiritual growth pathway detail page" },
  { path: "/pathways/[slug]/steps/[stepSlug]", purpose: "Individual pathway step page" },
  { path: "/sacraments", purpose: "Sacrament Preparation Companion overview" },
  { path: "/sacraments/companion", purpose: "Browse sacrament preparation companions" },
  { path: "/sacraments/prepare", purpose: "LocalStorage sacrament preparation wizard" },
  { path: "/sacraments/my-preparation", purpose: "Saved local sacrament preparation progress" },
  { path: "/sacraments/print", purpose: "Printable/exportable preparation plan" },
  { path: "/sacraments/[slug]", purpose: "Specific sacrament preparation companion" },
  { path: "/confession", purpose: "Gentle Catholic Confession Guide hub with preparation, examination, prayers, and support" },
  { path: "/confession/examination", purpose: "Private local-only Guided Examination of Conscience" },
  { path: "/confession/examination/start", purpose: "Choose examination mode, state of life, and paths" },
  { path: "/confession/examination/ten-commandments", purpose: "Ten Commandments examination prompts" },
  { path: "/confession/examination/beatitudes", purpose: "Beatitudes examination prompts" },
  { path: "/confession/examination/state-of-life", purpose: "State of life, duties, prayer, sacramental life, and works of mercy prompts" },
  { path: "/confession/examination/virtues", purpose: "Virtues and vices examination prompts" },
  { path: "/confession/examination/review", purpose: "Review marked prompts and private local notes" },
  { path: "/confession/how-to-go", purpose: "Pastoral guide for going to confession" },
  { path: "/confession/sins", purpose: "Pastoral overview of sin, conscience, culpability, and conversion" },
  { path: "/confession/habitual-sin", purpose: "Gentle support for habitual sin, safeguards, confession, and contrary virtues" },
  { path: "/confession/resisting-temptation", purpose: "Practical Catholic guide for resisting temptation before consent" },
  { path: "/confession/predominant-fault", purpose: "Self-knowledge guide for naming a recurring fault and practicing a contrary virtue" },
  { path: "/confession/prayers", purpose: "Original prayers before and after confession" },
  { path: "/virtue-tracker", purpose: "Private local-only Virtue and Vice Tracker overview" },
  { path: "/virtue-tracker/dashboard", purpose: "Saved local check-ins and gentle dashboard summary" },
  { path: "/virtue-tracker/check-in", purpose: "Private local virtue and vice check-in flow" },
  { path: "/virtue-tracker/virtues", purpose: "Theological, cardinal, and contrary virtue library" },
  { path: "/virtue-tracker/vices", purpose: "Capital vice library with contrary virtues" },
  { path: "/virtue-tracker/patterns", purpose: "Private pattern summary without scores or streaks" },
  { path: "/virtue-tracker/confession-prep", purpose: "Private check-ins marked for confession preparation" },
  { path: "/virtue-tracker/settings", purpose: "Local settings, export, and delete controls" },
  { path: "/saints", purpose: "Catholic Saints Library, saint companion hub, virtues, patronages, and holiness formation" },
  { path: "/saints/finder", purpose: "Saint companion finder by need, virtue, and state of life" },
  { path: "/saints/calendar", purpose: "Saint feast day calendar" },
  { path: "/saints/patron-saints", purpose: "Patron saints directory by need, vocation, and state of life" },
  { path: "/saints/virtues", purpose: "Browse saints by virtue and weekly practices" },
  { path: "/saints/reading-plan", purpose: "Beginner saint reading path and 7-day challenge" },
  { path: "/saints/confirmation", purpose: "Confirmation saint helper and companion guide" },
  { path: "/saints/saint-of-the-day", purpose: "Saint of the day page with trusted sources" },
  { path: "/saints/companions", purpose: "Saved local saint companions" },
  { path: "/saints/patronage", purpose: "Saint patronage groups" },
  { path: "/saints/settings", purpose: "Local companion export/delete and Google Sheets saint schema" },
  { path: "/saints/[slug]", purpose: "Saint profile page" },
  { path: "/community/events", purpose: "Upcoming Daily Oratory prayer, formation, and local Catholic community events" },
  { path: "/community/events/[slug]", purpose: "Event detail with schedule, location, recurrence, preparation notes, and related resources" },
  { path: "/community/local-faith-groups", purpose: "Directory pattern for local Catholic prayer groups and formation circles" },
  { path: "/community/group-discussion-topics", purpose: "Prayerful Catholic discussion topics for families, parish groups, and formation teams" },
  { path: "/community/contact", purpose: "Community contact form placeholder for listings, events, and support questions" },
  { path: "/adoration", purpose: "Live Adoration Portal with featured, live, 24/7, and verified streams" },
  { path: "/adoration/live", purpose: "Filtered live and 24/7 Eucharistic Adoration streams" },
  { path: "/adoration/[slug]", purpose: "Stream detail prayer chapel with quiet mode, safe iframe, prayer panel, and reporting" },
  { path: "/adoration/prayers", purpose: "Adoration prayer panel for entering, silence, reparation, and leaving" },
  { path: "/adoration/submit-stream", purpose: "Local submit-stream review form plus Google Sheets schema and Apps Script plan" },
  { path: "/prayer-intentions", purpose: "Prayer intentions overview, privacy notes, and moderation-first ask for prayer flow" },
  { path: "/prayer-intentions/submit", purpose: "Local mock prayer intention submission form with privacy warnings" },
  { path: "/prayer-intentions/wall", purpose: "Legacy prayer wall path redirected to the main prayer intentions page" },
  { path: "/prayer-intentions/urgent", purpose: "Approved urgent public intentions with emergency disclaimer" },
  { path: "/prayer-intentions/thanksgivings", purpose: "Approved thanksgiving intentions" },
  { path: "/prayer-intentions/guidelines", purpose: "Moderation workflow, Google Sheets workflow, and Supabase-ready schema" },
  { path: "/prayer-intentions/[slug]", purpose: "Approved public prayer intention detail page" },
  { path: "/library", purpose: "All resources with search, category, tag, and season filters" },
  { path: "/library/[slug]", purpose: "Canonical resource detail page" },
  { path: "/about", purpose: "Mission, editorial posture, brand trust" },
  { path: "/mission", purpose: "How the Church prays, forms vocations, spreads the Gospel, and serves those in need" },
  { path: "/spiritual-warfare", purpose: "Catholic guidance on spiritual warfare, ordinary means of grace, discernment, and deliverance help" },
  { path: "/contact", purpose: "Corrections, contributions, and inquiries" },
] as const;
