export type NavigationItem = {
  label: string;
  href: string;
  description?: string;
};

export type NavigationGroup = {
  title: string;
  children: NavigationItem[];
};

export { legacyRedirects, redirectMap, type RedirectRule } from "@/data/redirects";

export type NavigationSection = NavigationItem & {
  children: NavigationItem[];
  groups?: NavigationGroup[];
};

export const siteNavigation: NavigationSection[] = [
  {
    label: "Start Here",
    href: "/catholic-life",
    description: "See how prayer, Mass, Confession, formation, and daily Catholic life fit together.",
    children: [
      { label: "What Should I Do?", href: "/what-should-i-do", description: "Choose your situation and find one faithful next step." },
      { label: "Catholic Life Roadmap", href: "/catholic-life", description: "A simple roadmap through Catholic prayer, sacraments, formation, mercy, and hope." },
      { label: "Catholic Q&A", href: "/catholic-answers", description: "Short beginner-friendly Catholic answers with links to deeper guides." },
      { label: "Sacramental Emergency", href: "/sacramental-emergency", description: "What to do when someone needs a priest, Confession, Anointing, or prayer urgently." },
      { label: "Explore the Catholic Faith", href: "/explore", description: "A welcoming starting place for first questions and next steps." },
      { label: "Becoming Catholic", href: "/ocia", description: "The parish path into full communion." },
      { label: "Returning Catholics", href: "/returning", description: "A calm guide for coming home to the Church." },
      { label: "Formation", href: "/formation", description: "Grow in doctrine, virtue, prayer, and daily discipleship." },
    ],
  },
  {
    label: "Pray",
    href: "/prayers",
    description: "Begin in prayer and keep a daily Catholic rhythm.",
    children: [
      { label: "Begin in Prayer", href: "/begin-in-prayer", description: "A simpler start page with direct prayers and a calmer first step into Catholic prayer." },
      { label: "Prayer Library", href: "/prayers", description: "Find Catholic prayers for daily life, Confession, the Rosary, the dead, and more." },
      { label: "Litanies", href: "/prayers/litanies", description: "Learn what Catholic litanies are, how to pray them, and which traditional litanies fit different needs." },
      { label: "The Angelus", href: "/prayers/angelus", description: "A traditional Marian prayer for morning, noon, and evening outside the Easter season." },
      { label: "Regina Caeli", href: "/prayers/regina-caeli", description: "The Easter Marian prayer traditionally prayed from Easter through Pentecost." },
      { label: "Devotions", href: "/devotions", description: "Discover Catholic devotions ordered to Christ, the sacraments, and daily fidelity." },
      { label: "Scripture Prayer", href: "/library/scripture-prayer", description: "Pray with the Word of God through Scripture, Mass readings, and Lectio Divina." },
      { label: "Daily Examen", href: "/daily-examen", description: "End the day with gratitude, mercy, reflection, and peaceful trust in God." },
      { label: "Liturgy of the Hours", href: "/liturgy-of-the-hours", description: "Learn the Divine Office and pray the Church's daily hours." },
      { label: "Saint Companion", href: "/saints/finder", description: "Find a saint companion for prayer, virtue, and discipleship." },
      { label: "The Holy Mass", href: "/mass", description: "Understand the Mass as sacrifice, worship, communion, and heaven touching earth." },
      { label: "Sacramental Emergency", href: "/sacramental-emergency", description: "Urgent Catholic help for serious illness, danger of death, Confession, and prayer." },
      { label: "Family Prayer", href: "/family", description: "Build a home of prayer, mercy, and steady Catholic family rhythms." },
      { label: "Holy Rosary", href: "/rosary", description: "Pray the mysteries with Mary." },
      { label: "Divine Mercy Chaplet", href: "/divine-mercy", description: "A quiet Chaplet room for mercy and trust." },
      { label: "Way of the Cross", href: "/way-of-cross", description: "Pray the Stations of the Cross with Christ." },
      { label: "Live Adoration", href: "/adoration", description: "Enter Adoration with reverence." },
      { label: "Eucharistic Miracles", href: "/eucharistic-miracles", description: "Study signs of Christ's Eucharistic presence." },
      { label: "Confession Guide", href: "/confession", description: "Prepare for the sacrament of mercy." },
    ],
  },
  {
    label: "Reflect",
    href: "/reflections",
    description: "Receive Scripture and examine the day with peace.",
    children: [
      { label: "Mass Readings Reflections", href: "/reflections/mass-readings", description: "Daily Mass, Sunday Mass, solemnity, and feast day reflections." },
      {
        label: "Guided Examination of Conscience",
        href: "/confession/examination",
        description: "Review the day before God.",
      },
      {
        label: "Homilies",
        href: "/homilies",
        description: "Listen to Catholic homilies, Gospel reflections, and preaching playlists.",
      },
      {
        label: "Virtue and Vice Tracker",
        href: "/virtue-tracker",
        description: "Notice patterns and grow in virtue.",
      },
    ],
  },
  {
    label: "Learn",
    href: "/learn",
    description: "Grow in Catholic teaching, devotion, and sacramental life.",
    groups: [
      {
        title: "Start Here",
        children: [
          { label: "Explore the Catholic Faith", href: "/explore", description: "A gentle starting point for questions and first steps." },
          { label: "Catholic Life Roadmap", href: "/catholic-life", description: "A simple map through Catholic prayer, sacraments, formation, and daily life." },
          { label: "Becoming Catholic", href: "/ocia", description: "OCIA and the parish path into full communion." },
          { label: "Returning Catholics", href: "/returning", description: "A calm guide for coming home to the Church." },
          { label: "First Time at Mass", href: "/explore/first-time-at-mass", description: "What to expect and how to participate respectfully." },
          { label: "Glossary", href: "/glossary", description: "Simple Catholic terms in plain English." },
        ],
      },
      {
        title: "Core Faith",
        children: [
          { label: "Bible", href: "/bible", description: "Learn how Catholics read Sacred Scripture with the Church." },
          { label: "Body, Soul, and Spirit", href: "/body-soul-spirit", description: "Understand the human person, grace, sin, Confession, and the soul as an interior temple of God." },
          { label: "Catechism", href: "/catechism", description: "What the Church teaches and how to use it." },
          { label: "The Holy Mass", href: "/mass", description: "The shape and meaning of Catholic worship." },
          { label: "Sacraments", href: "/sacraments", description: "The seven sacraments and how Christ acts through them." },
          { label: "Sacramentals", href: "/sacramentals", description: "Holy water, rosaries, medals, scapulars, crucifixes, blessings, and daily Catholic life." },
          { label: "Relics", href: "/relics", description: "Learn what relics are, why Catholics venerate them, and why they must never be treated superstitiously." },
          { label: "Sacred Tradition", href: "/tradition", description: "How the apostolic faith is handed on in the Church." },
          { label: "The Pope", href: "/pope", description: "The Petrine ministry and visible unity of the Church." },
        ],
      },
      {
        title: "Church Life and History",
        children: [
          { label: "Councils of the Church", href: "/councils", description: "How councils clarified doctrine and guided the Church." },
          { label: "The Vatican", href: "/vatican", description: "Vatican City, Saint Peter's Basilica, and official Vatican resources." },
          { label: "Church Fathers", href: "/church-fathers", description: "Early Christian witnesses to Scripture, worship, and doctrine." },
          { label: "Catholic News", href: "/news", description: "Faithful news and official Church sources." },
          { label: "Scripture Prayer", href: "/library/scripture-prayer", description: "How Catholics pray with the Word of God." },
          { label: "Homilies", href: "/homilies", description: "Catholic homilies, reflections, and preaching playlists for prayer and formation." },
          { label: "Media Library", href: "/media", description: "Videos, playlists, slides, images, and Catholic formation resources." },
        ],
      },
      {
        title: "Spiritual Growth",
        children: [
          { label: "Formation", href: "/formation", description: "Doctrine, virtue, prayer, and steady discipleship." },
          { label: "Grace", href: "/formation/grace", description: "Learn about sanctifying grace, actual grace, sacramental grace, charisms, and cooperation with grace." },
          { label: "Catholic Eschatology", href: "/formation/eschatology", description: "A hopeful guide to death, judgment, Heaven, Hell, Purgatory, resurrection, and Christ's return." },
          { label: "Catholic Burial", href: "/formation/catholic-burial", description: "Burial, cremation, funeral rites, prayers for the dead, and planning with hope in the resurrection." },
          { label: "Sin & Temptation", href: "/sin-and-temptation", description: "Understand sin, resist temptation, seek mercy, and grow in healing and virtue." },
          { label: "Spiritual Warfare", href: "/spiritual-warfare", description: "A calm Catholic guide to spiritual warfare, deliverance, and when to seek parish or diocesan help." },
          { label: "Angels", href: "/angels", description: "Learn what the Church teaches about angels, guardian angels, and the invisible world." },
          { label: "Relics", href: "/relics", description: "A reverent guide to relics, reliquaries, and the communion of saints." },
          { label: "Saints", href: "/saints", description: "Holy men and women who still encourage the Church." },
          { label: "Catholic Devotions", href: "/devotions", description: "Traditional devotions ordered toward Christ." },
          { label: "Family and Domestic Church", href: "/family", description: "Prayer and formation in Catholic family life." },
          { label: "Indulgences", href: "/indulgences", description: "A practical guide to indulgences and their conditions." },
          { label: "Detachment from Sin", href: "/indulgences/detachment-from-sin", description: "A gentle guide to the interior freedom sought in conversion and plenary indulgences." },
          { label: "Indulgence Prayers and Devotions", href: "/indulgences/prayers-and-devotions", description: "Traditional Catholic prayers and devout works associated with indulgences under the Church's norms." },
          { label: "Daily Rule of Life", href: "/rule-of-life", description: "A simple Catholic rhythm of prayer and mercy." },
          { label: "Spiritual Growth Pathways", href: "/pathways", description: "Guided tracks for formation and conversion." },
          { label: "Heavenbound Companion", href: "/tools/heavenbound", description: "An external Catholic spiritual companion in ChatGPT." },
        ],
      },
    ],
    children: [
      { label: "Spiritual Growth Pathways", href: "/pathways", description: "Guided Catholic formation tracks." },
      { label: "Heavenbound Companion", href: "/tools/heavenbound", description: "Choose a Catholic spiritual path and open Heavenbound in ChatGPT." },
      { label: "Daily Rule of Life", href: "/rule-of-life", description: "Prayer, Scripture, virtue, sacraments, and mercy." },
      { label: "Explore the Catholic Faith", href: "/explore", description: "A welcoming starting place for anyone curious about Catholic belief, prayer, worship, and spiritual life." },
      { label: "Catholic Life Roadmap", href: "/catholic-life", description: "A master start-here guide to prayer, Mass, Confession, Scripture, grace, family faith, and hope." },
      { label: "Indulgences", href: "/indulgences", description: "A practical Catholic guide to indulgences, the usual conditions, and special grace years." },
      { label: "Detachment from Sin", href: "/indulgences/detachment-from-sin", description: "A gentle guide to complete detachment from sin, conversion, and spiritual freedom." },
      { label: "Indulgence Prayers and Devotions", href: "/indulgences/prayers-and-devotions", description: "A guide to prayers, Scripture reading, and devotions traditionally associated with indulgences." },
      { label: "Catholic Devotions", href: "/devotions", description: "Learn the meaning, purpose, and practice of traditional Catholic devotions." },
      { label: "Church Fathers", href: "/church-fathers", description: "Discover the early witnesses of the Church and learn how they taught Scripture, sacraments, prayer, virtue, and doctrine." },
      { label: "Bible", href: "/bible", description: "Learn how Catholics read the Bible, pray with Mass readings, and choose Catholic translations." },
      { label: "Body, Soul, and Spirit", href: "/body-soul-spirit", description: "Understand the human person, grace, sin, Confession, and the soul as an interior temple of God." },
      { label: "Catechism", href: "/catechism", description: "Learn what the Church teaches, how the Catechism is organized, and how to use it for prayer, study, and formation." },
      { label: "Sacred Tradition", href: "/tradition", description: "Understand how the Catholic faith is handed on through Scripture, apostolic teaching, worship, sacraments, saints, and the guidance of the Holy Spirit." },
      { label: "Councils of the Church", href: "/councils", description: "Learn how the bishops of the Church gathered in councils to defend the faith, clarify doctrine, guide worship, address errors, and help the Church follow Christ through history." },
      { label: "Family and Domestic Church", href: "/family", description: "Build a Catholic home of prayer, mercy, virtue, sacramental life, and family formation." },
      { label: "Angels and the Invisible World", href: "/angels", description: "Learn what the Church teaches about angels, guardian angels, worship, and spiritual protection." },
      { label: "The Pope", href: "/pope", description: "Understand the Pope's role as Bishop of Rome, successor of Saint Peter, and visible sign of unity in the Church." },
      { label: "The Vatican", href: "/vatican", description: "Explore Vatican City, Saint Peter's Basilica, Vatican history, sacred art, virtual tours, and official Vatican media." },
      { label: "Sacraments", href: "/sacraments", description: "Prepare for grace with parish guidance." },
      { label: "Sacramentals", href: "/sacramentals", description: "Learn how blessed signs and objects help daily life become prayer." },
      { label: "Relics", href: "/relics", description: "Learn how relics connect the saints, the body, and the hope of resurrection." },
      { label: "Becoming Catholic", href: "/ocia", description: "Learn about OCIA, the parish journey for adults exploring the Catholic faith or preparing for initiation." },
      { label: "Saints", href: "/saints", description: "Meet the holy men and women who followed Christ and still encourage the Church." },
      { label: "Catholic News", href: "/news", description: "Follow Catholic news, official Church sources, and faith updates with prayerful discernment." },
      { label: "Scripture Prayer", href: "/library/scripture-prayer", description: "Learn how Catholics read, pray, and live the Word of God." },
      { label: "Media Library", href: "/media", description: "Explore Catholic videos, slides, images, playlists, and formation resources." },
      { label: "The Holy Mass", href: "/mass", description: "Learn the parts of the Mass, sacred spaces, Real Presence, and prayerful participation." },
      { label: "Formation", href: "/formation", description: "Grow in doctrine, virtue, prayer, and daily discipleship." },
      { label: "Grace", href: "/formation/grace", description: "Understand God’s gift of divine life, healing, help, and holiness." },
      { label: "Catholic Eschatology", href: "/formation/eschatology", description: "A hopeful Catholic guide to the last things and eternal life in Christ." },
      { label: "Catholic Burial", href: "/formation/catholic-burial", description: "A gentle guide to burial, cremation, funeral rites, and prayers for the dead." },
      { label: "Sin & Temptation", href: "/sin-and-temptation", description: "A Catholic guide to sin, temptation, confession, healing, and conversion." },
      { label: "Spiritual Warfare", href: "/spiritual-warfare", description: "A calm Catholic guide to spiritual warfare, deliverance, and when to seek parish or diocesan help." },
    ],
  },
  {
    label: "Media",
    href: "/media",
    description: "Videos, slides, images, and Catholic formation resources.",
    children: [
      { label: "Media Library", href: "/media", description: "Browse Catholic videos, slides, images, playlists, and formation resources." },
      { label: "Prophecy Series", href: "/prophecy-series", description: "Follow the 12-part Sunday evening Prophecy Series with playlist, schedule, and discernment notes." },
      { label: "Homilies", href: "/homilies", description: "Homilies, preaching playlists, and audio reflections." },
      { label: "Formation", href: "/formation", description: "Grow in doctrine, virtue, prayer, and daily discipleship." },
      { label: "The Holy Mass", href: "/mass", description: "Learn the parts of the Mass, sacred spaces, and prayerful participation." },
      { label: "Adoration", href: "/adoration", description: "Pray before Jesus in Eucharistic Adoration." },
      { label: "Scripture Prayer", href: "/library/scripture-prayer", description: "Pray with the Word of God through Scripture and reflection." },
      { label: "Explore the Catholic Faith", href: "/explore", description: "A gentle place to begin if you are curious about Catholicism." },
    ],
  },
  {
    label: "Liturgical Year",
    href: "/liturgical-living",
    description: "Live the liturgical year with the Church.",
    children: [
      { label: "Today in the Church", href: "/today", description: "Seasonal focus for prayer and life." },
      { label: "Faith News", href: "/news", description: "Follow the life of the Church with prayer, charity, and discernment." },
      {
        label: "Liturgical Living Dashboard",
        href: "/liturgical-living",
        description: "Calendar, colors, seasons, and practices.",
      },
      { label: "Calendar", href: "/liturgical-living/calendar", description: "Follow feasts and seasons." },
      { label: "Seasons", href: "/liturgical-living/seasons", description: "Advent, Lent, Easter, and Ordinary Time." },
      { label: "O Antiphons", href: "/liturgical-living/advent/o-antiphons", description: "Pray the ancient Advent titles of Christ from December 17–23." },
      { label: "Lent", href: "/liturgical-living/lent", description: "Prayer, fasting, repentance, and preparation for Easter." },
      { label: "Christmas Season", href: "/liturgical-living/christmas", description: "Celebrate the Incarnation through Christmas, Epiphany, and the Lord's light." },
      { label: "Epiphany", href: "/liturgical-living/christmas/epiphany", description: "Follow the Magi, worship Christ, and bless the home during Epiphany." },
      { label: "Saint of the Day", href: "/saints/saint-of-the-day", description: "Meet today’s saint and continue in prayer." },
      { label: "Holy Days", href: "/liturgical-living/holy-days", description: "Mark solemn days with prayer." },
      {
        label: "Family Liturgical Living",
        href: "/liturgical-living/family",
        description: "Simple domestic Church practices.",
      },
    ],
  },
  {
    label: "Library",
    href: "/library",
    description: "Search all Daily Oratory resources.",
    children: [
      { label: "All Resources", href: "/library", description: "Search the full Catholic library." },
      { label: "Bible", href: "/bible", description: "A Catholic guide to Scripture, translations, Mass readings, and Bible prayer." },
      { label: "Scripture Prayer", href: "/library/scripture-prayer", description: "Read the Bible with the Church and pray with the Word of God." },
      { label: "Prayer Resources", href: "/library?q=prayer", description: "Prayers, Rosary, Adoration, and devotion." },
      { label: "Formation Resources", href: "/library?q=formation", description: "Virtue, doctrine, and spiritual growth." },
      { label: "Sacramental Resources", href: "/library?q=sacraments", description: "Mass, confession, Eucharist, and preparation." },
      { label: "Seasonal Resources", href: "/library?q=liturgical%20year", description: "Advent, Lent, Easter, and Church seasons." },
    ],
  },
  {
    label: "Community",
    href: "/community",
    description: "Find Catholic events, live prayer gatherings, and local faith groups.",
    children: [
      { label: "Community Home", href: "/community", description: "Prayer intentions, events, groups, and Catholic community support." },
      { label: "Events", href: "/community/events", description: "Upcoming Catholic prayer, formation, and community gatherings." },
      { label: "Local Faith Groups", href: "/community/local-faith-groups", description: "Find Catholic groups, circles, and parish gatherings." },
      { label: "Discussion Topics", href: "/community/group-discussion-topics", description: "Prayerful prompts for parish groups and Catholic conversation." },
      { label: "Community Contact", href: "/community/contact", description: "Questions about event listings, groups, and community support." },
    ],
  },
  {
    label: "About",
    href: "/about",
    description: "The mission and editorial posture of Daily Oratory.",
    children: [
      { label: "Mission", href: "/mission", description: "How the Church prays, forms vocations, and serves in charity." },
      { label: "Contact", href: "/contact", description: "Corrections, contributions, and event inquiries." },
    ],
  },
];

export const primaryNavigation = siteNavigation.map(({ label, href }) => ({ label, href }));

export const desktopMegaMenu = siteNavigation;

export const mobileDrawerNavigation = siteNavigation;

export const footerNavigationGroups = [
  {
    title: "Helpful Guides",
    links: [
      { label: "What Should I Do?", href: "/what-should-i-do" },
      { label: "Catholic Life Roadmap", href: "/catholic-life" },
      { label: "Catholic Q&A", href: "/catholic-answers" },
      { label: "Prayer Library", href: "/prayers" },
      { label: "Begin in Prayer", href: "/begin-in-prayer" },
      { label: "Litanies", href: "/prayers/litanies" },
      { label: "Confession Guide", href: "/confession" },
      { label: "Holy Rosary", href: "/devotions/holy-rosary" },
      { label: "Sacramental Emergency", href: "/sacramental-emergency" },
    ],
  },
  {
    title: "Begin",
    links: [
      { label: "Begin in prayer", href: "/begin-in-prayer" },
      { label: "Catholic Life Roadmap", href: "/catholic-life" },
      { label: "Enter Adoration", href: "/adoration" },
      { label: "Build a daily rule of life", href: "/rule-of-life" },
      { label: "Confession Guide", href: "/confession" },
    ],
  },
  {
    title: "Grow",
    links: [
      { label: "Mass Readings Reflections", href: "/reflections/mass-readings" },
      { label: "Live the liturgical year", href: "/liturgical-living" },
      { label: "Sacrament Companion", href: "/sacraments" },
      { label: "Grow in virtue", href: "/virtue-tracker" },
      { label: "Find a saint companion", href: "/saints" },
    ],
  },
  {
    title: "Gather",
    links: [
      { label: "Library", href: "/library" },
      { label: "Events", href: "/community/events" },
      { label: "Community", href: "/community" },
    ],
  },
] as const;

export const breadcrumbPatterns = [
  { pattern: "/", label: "Home" },
  { pattern: "/what-should-i-do", label: "What Should I Do?" },
  { pattern: "/catholic-life", label: "Catholic Life Roadmap" },
  { pattern: "/catholic-answers", label: "Catholic Q&A" },
  { pattern: "/pray", label: "Pray" },
  { pattern: "/begin-in-prayer", label: "Begin in Prayer" },
  { pattern: "/prayers", label: "Prayer Library" },
  { pattern: "/prayers/litanies", label: "Catholic Litanies" },
  { pattern: "/daily-examen", label: "Daily Examen" },
  { pattern: "/liturgy-of-the-hours", label: "Liturgy of the Hours" },
  { pattern: "/divine-office", label: "Divine Office" },
  { pattern: "/prayer/liturgy-of-the-hours", label: "Liturgy of the Hours" },
  { pattern: "/rosary", label: "Rosary" },
  { pattern: "/rosary/joyful-mysteries", label: "Joyful Mysteries" },
  { pattern: "/rosary/sorrowful-mysteries", label: "Sorrowful Mysteries" },
  { pattern: "/rosary/glorious-mysteries", label: "Glorious Mysteries" },
  { pattern: "/rosary/luminous-mysteries", label: "Luminous Mysteries" },
  { pattern: "/rosary/latin-rosary", label: "Latin Rosary" },
  { pattern: "/divine-mercy", label: "Divine Mercy" },
  { pattern: "/devotions", label: "Devotions" },
  { pattern: "/devotions/[slug]", label: "Devotion" },
  { pattern: "/library/scripture-prayer", label: "Scripture Prayer" },
  { pattern: "/mass", label: "The Holy Mass" },
  { pattern: "/holy-mass", label: "The Holy Mass" },
  { pattern: "/library/mass", label: "The Holy Mass" },
  { pattern: "/library/holy-mass", label: "The Holy Mass" },
  { pattern: "/way-of-cross", label: "Way of the Cross" },
  { pattern: "/eucharistic-miracles", label: "Eucharistic Miracles" },
  { pattern: "/eucharistic-stations", label: "Stations of the Eucharist" },
  { pattern: "/resurrection-stations", label: "Stations of the Resurrection" },
  { pattern: "/reflect", label: "Reflect" },
  { pattern: "/reflections", label: "Mass Readings Reflections" },
  { pattern: "/reflections/mass-readings", label: "Mass Readings Reflections" },
  { pattern: "/reflections/mass-readings/archive", label: "Archive" },
  { pattern: "/reflections/mass-readings/calendar", label: "Calendar" },
  { pattern: "/reflections/mass-readings/upcoming", label: "Upcoming" },
  { pattern: "/reflections/mass-readings/[slug]", label: "Mass Reading Reflection" },
  { pattern: "/reflections/daily", label: "Daily Mass Reflections" },
  { pattern: "/reflections/sunday", label: "Sunday Mass Reflections" },
  { pattern: "/reflections/[slug]", label: "Reflection" },
  { pattern: "/learn", label: "Learn" },
  { pattern: "/bible", label: "Bible" },
  { pattern: "/body-soul-spirit", label: "Body, Soul, and Spirit" },
  { pattern: "/sin-and-temptation", label: "Sin & Temptation" },
  { pattern: "/spiritual-warfare", label: "Spiritual Warfare" },
  { pattern: "/sin-and-temptation/venial-and-mortal-sin", label: "Venial and Mortal Sin" },
  { pattern: "/sin-and-temptation/habitual-sin", label: "Habitual Sin" },
  { pattern: "/sin-and-temptation/predominant-fault", label: "Predominant Fault" },
  { pattern: "/sin-and-temptation/resisting-temptation", label: "Resisting Temptation" },
  { pattern: "/sin-and-temptation/near-occasions-of-sin", label: "Near Occasions of Sin" },
  { pattern: "/sin-and-temptation/examination-and-confession", label: "Examination and Confession" },
  { pattern: "/sin-and-temptation/virtue-and-healing", label: "Virtue and Healing" },
  { pattern: "/angels", label: "Angels and the Invisible World" },
  { pattern: "/sacramentals", label: "Sacramentals" },
  { pattern: "/relics", label: "Relics" },
  { pattern: "/media", label: "Media Library" },
  { pattern: "/prophecy-series", label: "Prophecy Series" },
  { pattern: "/media/prophecy-series", label: "Prophecy Series" },
  { pattern: "/media/[slug]", label: "Media Item" },
  { pattern: "/homilies", label: "Homilies" },
  { pattern: "/news", label: "Catholic News" },
  { pattern: "/explore", label: "Explore the Catholic Faith" },
  { pattern: "/explore/first-time-at-mass", label: "First Time at Mass" },
  { pattern: "/explore/questions", label: "Common Questions" },
  { pattern: "/returning", label: "Returning Catholics" },
  { pattern: "/glossary", label: "Glossary" },
  { pattern: "/catechism", label: "Catechism" },
  { pattern: "/ocia", label: "Becoming Catholic" },
  { pattern: "/tradition", label: "Sacred Tradition" },
  { pattern: "/family", label: "The Domestic Church" },
  { pattern: "/pope", label: "The Pope" },
  { pattern: "/vatican", label: "The Vatican" },
  { pattern: "/formation", label: "Formation" },
  { pattern: "/formation/grace", label: "Grace" },
  { pattern: "/formation/grace/sanctifying-grace", label: "Sanctifying Grace" },
  { pattern: "/formation/grace/actual-grace", label: "Actual Grace" },
  { pattern: "/formation/grace/sacramental-grace", label: "Sacramental Grace" },
  { pattern: "/formation/grace/charisms", label: "Charisms" },
  { pattern: "/formation/grace/cooperating-with-grace", label: "Cooperating with Grace" },
  { pattern: "/church-fathers", label: "Church Fathers" },
  { pattern: "/indulgences", label: "Indulgences" },
  { pattern: "/tools", label: "Tools" },
  { pattern: "/tools/heavenbound", label: "Heavenbound Companion" },
  { pattern: "/liturgical-year", label: "Liturgical Year" },
  { pattern: "/today", label: "Today in the Church" },
  { pattern: "/dashboard", label: "Dashboard" },
  { pattern: "/liturgical-living", label: "Liturgical Living" },
  { pattern: "/liturgical-living/lent", label: "Lent" },
  { pattern: "/liturgical-living/calendar", label: "Calendar" },
  { pattern: "/liturgical-living/seasons", label: "Seasons" },
  { pattern: "/liturgical-living/advent", label: "Advent" },
  { pattern: "/liturgical-living/advent/o-antiphons", label: "O Antiphons" },
  { pattern: "/liturgical-living/christmas", label: "Christmas" },
  { pattern: "/liturgical-living/christmas/epiphany", label: "Epiphany" },
  { pattern: "/liturgical-living/christmas/epiphany/house-blessing", label: "House Blessing" },
  { pattern: "/liturgical-living/holy-days", label: "Holy Days" },
  { pattern: "/liturgical-living/family", label: "Family" },
  { pattern: "/liturgical-living/settings", label: "Settings" },
  { pattern: "/rule-of-life", label: "Rule of Life" },
  { pattern: "/rule-of-life/builder", label: "Builder" },
  { pattern: "/rule-of-life/my-rule", label: "My Rule" },
  { pattern: "/rule-of-life/templates", label: "Templates" },
  { pattern: "/rule-of-life/examen", label: "Daily Examen" },
  { pattern: "/rule-of-life/print", label: "Print" },
  { pattern: "/pathways", label: "Pathways" },
  { pattern: "/pathways/start", label: "Start" },
  { pattern: "/pathways/my-pathways", label: "My Pathways" },
  { pattern: "/pathways/recommended", label: "Recommended" },
  { pattern: "/pathways/settings", label: "Settings" },
  { pattern: "/pathways/[slug]", label: "Pathway" },
  { pattern: "/pathways/[slug]/steps/[stepSlug]", label: "Pathway Step" },
  { pattern: "/sacraments", label: "Sacraments" },
  { pattern: "/sacraments/baptism", label: "Baptism" },
  { pattern: "/sacraments/confirmation", label: "Confirmation" },
  { pattern: "/sacraments/eucharist", label: "Eucharist" },
  { pattern: "/sacraments/eucharist/mass", label: "The Holy Mass" },
  { pattern: "/sacraments/reconciliation", label: "Reconciliation" },
  { pattern: "/sacraments/anointing", label: "Anointing of the Sick" },
  { pattern: "/sacraments/matrimony", label: "Matrimony" },
  { pattern: "/sacraments/marriage", label: "Marriage" },
  { pattern: "/sacraments/holy-orders", label: "Holy Orders" },
  { pattern: "/sacraments/ocia", label: "OCIA" },
  { pattern: "/sacraments/sponsor-godparent", label: "Sponsor and Godparent Guide" },
  { pattern: "/sacraments/first-communion", label: "First Communion" },
  { pattern: "/sacraments/companion", label: "Companion" },
  { pattern: "/sacraments/prepare", label: "Prepare" },
  { pattern: "/sacraments/my-preparation", label: "My Preparation" },
  { pattern: "/sacraments/print", label: "Print" },
  { pattern: "/sacraments/[slug]", label: "Sacrament Companion" },
  { pattern: "/confession", label: "Confession Guide" },
  { pattern: "/confession/examination", label: "Guided Examination" },
  { pattern: "/confession/examination/start", label: "Start" },
  { pattern: "/confession/examination/ten-commandments", label: "Ten Commandments" },
  { pattern: "/confession/examination/beatitudes", label: "Beatitudes" },
  { pattern: "/confession/examination/state-of-life", label: "State of Life" },
  { pattern: "/confession/examination/virtues", label: "Virtues" },
  { pattern: "/confession/examination/review", label: "Review" },
  { pattern: "/confession/how-to-go", label: "How to Go to Confession" },
  { pattern: "/confession/sins", label: "Sins" },
  { pattern: "/confession/habitual-sin", label: "Habitual Sin" },
  { pattern: "/confession/resisting-temptation", label: "Resisting Temptation" },
  { pattern: "/confession/predominant-fault", label: "Predominant Fault" },
  { pattern: "/confession/prayers", label: "Confession Prayers" },
  { pattern: "/catholic-life", label: "Catholic Life Roadmap" },
  { pattern: "/sacramental-emergency", label: "Sacramental Emergency Guide" },
  { pattern: "/indulgences", label: "Indulgences" },
  { pattern: "/indulgences/detachment-from-sin", label: "Complete Detachment from Sin" },
  { pattern: "/formation/catholic-burial", label: "Catholic Burial" },
  { pattern: "/formation/catholic-burial/cremation", label: "Cremation" },
  { pattern: "/formation/catholic-burial/funeral-rites", label: "Funeral Rites" },
  { pattern: "/formation/catholic-burial/prayers-for-the-dead", label: "Prayers for the Dead" },
  { pattern: "/formation/catholic-burial/planning-a-catholic-funeral", label: "Planning a Catholic Funeral" },
  { pattern: "/virtue-tracker", label: "Virtue Tracker" },
  { pattern: "/virtue-tracker/dashboard", label: "Dashboard" },
  { pattern: "/virtue-tracker/check-in", label: "Check-in" },
  { pattern: "/virtue-tracker/virtues", label: "Virtues" },
  { pattern: "/virtue-tracker/vices", label: "Vices" },
  { pattern: "/virtue-tracker/patterns", label: "Patterns" },
  { pattern: "/virtue-tracker/confession-prep", label: "Confession Prep" },
  { pattern: "/virtue-tracker/settings", label: "Settings" },
  { pattern: "/saints", label: "Saints" },
  { pattern: "/saints/finder", label: "Finder" },
  { pattern: "/saints/calendar", label: "Saint Calendar" },
  { pattern: "/saints/patron-saints", label: "Patron Saints" },
  { pattern: "/saints/virtues", label: "Saints by Virtue" },
  { pattern: "/saints/reading-plan", label: "Saint Reading Plan" },
  { pattern: "/saints/confirmation", label: "Confirmation Saint Helper" },
  { pattern: "/saints/saint-of-the-day", label: "Saint of the Day" },
  { pattern: "/saints/companions", label: "Companions" },
  { pattern: "/saints/patronage", label: "Patronage" },
  { pattern: "/saints/settings", label: "Settings" },
  { pattern: "/saints/[slug]", label: "Saint Profile" },
  { pattern: "/community", label: "Community" },
  { pattern: "/ask-for-prayer", label: "Ask for Prayer" },
  { pattern: "/community/events", label: "Events" },
  { pattern: "/community/events/[slug]", label: "Event" },
  { pattern: "/community/local-faith-groups", label: "Local Faith Groups" },
  { pattern: "/community/group-discussion-topics", label: "Group Discussion Topics" },
  { pattern: "/community/contact", label: "Contact" },
  { pattern: "/adoration", label: "Adoration" },
  { pattern: "/adoration/live", label: "Live Adoration" },
  { pattern: "/adoration/[slug]", label: "Adoration Chapel" },
  { pattern: "/adoration/prayers", label: "Adoration Prayers" },
  { pattern: "/adoration/submit-stream", label: "Submit Stream" },
  { pattern: "/prayer-intentions", label: "Prayer Intentions" },
  { pattern: "/prayer-intentions/submit", label: "Submit" },
  { pattern: "/prayer-intentions/wall", label: "Prayer Intentions" },
  { pattern: "/prayer-intentions/urgent", label: "Urgent" },
  { pattern: "/prayer-intentions/thanksgivings", label: "Thanksgivings" },
  { pattern: "/prayer-intentions/guidelines", label: "Guidelines" },
  { pattern: "/prayer-intentions/[slug]", label: "Prayer Intention" },
  { pattern: "/library", label: "Library" },
  { pattern: "/library/[slug]", label: "Resource" },
  { pattern: "/about", label: "About" },
  { pattern: "/mission", label: "Mission" },
  { pattern: "/contact", label: "Contact" },
] as const;

export const urlStructure = [
  { path: "/", purpose: "Home and primary starting points" },
  { path: "/pray", purpose: "Prayer, Rosary, Adoration, prayer rooms, rule of life, confession" },
  { path: "/rosary", purpose: "Holy Rosary overview, how to pray, mystery selector, and day-of-week recommendation" },
  { path: "/rosary/joyful-mysteries", purpose: "Joyful Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/sorrowful-mysteries", purpose: "Sorrowful Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/glorious-mysteries", purpose: "Glorious Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/luminous-mysteries", purpose: "Luminous Mysteries with fruits, Scripture references, and meditation prompts" },
  { path: "/rosary/latin-rosary", purpose: "Latin Rosary guide with English cues and pronunciation help" },
  { path: "/divine-mercy", purpose: "Divine Mercy Chaplet quiet room with prayers and stream selector" },
  { path: "/devotions", purpose: "Catholic Devotions Library with featured devotions, needs-based recommendations, filters, and guidance" },
  { path: "/devotions/[slug]", purpose: "Catholic devotion detail page with pastoral guidance, trusted links, related tools, and source notes" },
  { path: "/way-of-cross", purpose: "Way of the Cross quiet room with St. Alphonsus Liguori station prayers and video meditation" },
  { path: "/eucharistic-miracles", purpose: "Eucharistic Miracles launch page linking to the external miracle catalog" },
  { path: "/eucharistic-stations", purpose: "Fourteen Stations of the Eucharist quiet room with prayers and video meditation" },
  { path: "/resurrection-stations", purpose: "Fourteen Stations of the Resurrection quiet room with video meditation and linked prayer booklet" },
  { path: "/reflect", purpose: "Daily and Sunday reflections, conscience, virtue and vice review" },
  { path: "/reflections", purpose: "Legacy alias that redirects to Mass Readings Reflections." },
  { path: "/reflections/mass-readings", purpose: "Mass Readings Reflections landing with today's reflection, Sunday Mass reflections, upcoming, archive, search, and filters" },
  { path: "/reflections/mass-readings/archive", purpose: "Archive of published Mass reading reflections grouped by month" },
  { path: "/reflections/mass-readings/calendar", purpose: "Calendar browsing for published and scheduled Mass reading reflections" },
  { path: "/reflections/mass-readings/upcoming", purpose: "Upcoming scheduled daily Mass, Sunday Mass, feast day, and solemnity reflections" },
  { path: "/reflections/mass-readings/[slug]", purpose: "Mass reading reflection detail with reading references, theology, prayer, and practical application" },
  { path: "/reflections/daily", purpose: "Legacy daily Mass reflections alias redirecting to filtered Mass Readings Reflections" },
  { path: "/reflections/sunday", purpose: "Legacy Sunday Mass reflections alias redirecting to filtered Mass Readings Reflections" },
  { path: "/reflections/[slug]", purpose: "Legacy reflection detail alias redirecting to canonical Mass Readings Reflection detail" },
  { path: "/learn", purpose: "Sacraments, saints, devotions, Scripture, Mass, formation" },
  { path: "/bible", purpose: "Catholic guide to Sacred Scripture, Bible translations, daily readings, and Scripture prayer" },
  { path: "/body-soul-spirit", purpose: "Catholic formation guide to the human person, grace, sin, Confession, Eucharist, and the soul as an interior temple of God" },
  { path: "/sin-and-temptation", purpose: "Catholic guide to sin, temptation, repentance, Confession, virtue, healing, and ongoing conversion" },
  { path: "/sin-and-temptation/venial-and-mortal-sin", purpose: "Pastoral guide to the distinction between venial and mortal sin" },
  { path: "/sin-and-temptation/habitual-sin", purpose: "Guide to repeated sin patterns, triggers, safeguards, and perseverance in grace" },
  { path: "/sin-and-temptation/predominant-fault", purpose: "Self-knowledge guide for identifying a recurring root weakness and contrary virtue" },
  { path: "/sin-and-temptation/resisting-temptation", purpose: "Practical Catholic guide and emergency plan for resisting temptation" },
  { path: "/sin-and-temptation/near-occasions-of-sin", purpose: "Guide to identifying and avoiding near occasions of sin" },
  { path: "/sin-and-temptation/examination-and-confession", purpose: "Guide to conscience, contrition, amendment, and Confession preparation" },
  { path: "/sin-and-temptation/virtue-and-healing", purpose: "Guide to opposite virtues, healing, sacramental life, and spiritual freedom" },
  { path: "/news", purpose: "Catholic news hub with official Church sources, trusted media links, and prayerful discernment" },
  { path: "/catechism", purpose: "Beginner-friendly Catechism guide with four pillars, topic finder, reading plan, and official Vatican and USCCB resources" },
  { path: "/angels", purpose: "Catholic guide to angels, guardian angels, archangels, heavenly worship, spiritual protection, and the invisible world" },
  { path: "/relics", purpose: "Catholic guide to relics, relic classes, reliquaries, veneration, pilgrimage, and the communion of saints" },
  { path: "/daily-examen", purpose: "Daily Examen guide for gratitude, mercy, review, trust, and peaceful night prayer" },
  { path: "/ocia", purpose: "Welcoming OCIA guide for adults exploring Catholicism, preparing for initiation, or seeking full communion" },
  { path: "/tradition", purpose: "Beginner-friendly guide to Sacred Tradition, Scripture, the Magisterium, apostolic succession, Church Fathers, and the deposit of faith" },
  { path: "/family", purpose: "Beginner-friendly guide to the domestic church, family prayer, family virtue, sacramental life, and Catholic formation in the home" },
  { path: "/pope", purpose: "Beginner-friendly guide to the Pope, papacy, papal documents, papal teaching, and prayer for the Holy Father" },
  { path: "/vatican", purpose: "Beginner-friendly guide to Vatican City, Saint Peter's Basilica, Vatican live broadcasts, sacred art, history, and virtual pilgrimage" },
  { path: "/mass", purpose: "The Holy Mass guide with liturgical walkthrough, sacred spaces, Real Presence, and prayerful participation" },
  { path: "/catholic-life", purpose: "Master start-here roadmap linking prayer, Mass, Confession, Scripture, grace, family faith, formation, and Catholic hope" },
  { path: "/sacramental-emergency", purpose: "Calm practical guide for urgent Catholic sacramental situations including danger of death, Anointing, Confession, Viaticum, and prayer" },
  { path: "/prophecy-series", purpose: "Daily Oratory Prophecy Series page with playlist, premiere schedule, episode tracker, prayer, and discernment guidance" },
  { path: "/formation/grace", purpose: "Catholic guide to grace, sanctifying grace, actual grace, sacramental grace, charisms, and cooperation with grace" },
  { path: "/formation/grace/sanctifying-grace", purpose: "Guide to sanctifying grace, holiness, Baptism, Eucharist, sin, and Confession" },
  { path: "/formation/grace/actual-grace", purpose: "Guide to God’s help in specific moments of temptation, repentance, prayer, and service" },
  { path: "/formation/grace/sacramental-grace", purpose: "Guide to sacramental grace and the grace proper to each sacrament" },
  { path: "/formation/grace/charisms", purpose: "Guide to charisms, special graces, discernment, humility, and service in the Church" },
  { path: "/formation/grace/cooperating-with-grace", purpose: "Guide to responding to grace through prayer, sacraments, virtue, and charity" },
  { path: "/formation/catholic-burial", purpose: "Catholic guide to burial, cremation, funeral rites, prayer for the dead, and funeral planning with hope in the resurrection" },
  { path: "/formation/catholic-burial/cremation", purpose: "Catholic cremation guide with reverent care for remains, interment guidance, and pastoral next steps" },
  { path: "/formation/catholic-burial/funeral-rites", purpose: "Guide to the Vigil, Funeral Mass, Rite of Committal, and family participation in Catholic funeral rites" },
  { path: "/formation/catholic-burial/prayers-for-the-dead", purpose: "Prayer page for deceased loved ones, souls in Purgatory, cemetery visits, anniversaries, and remembrance" },
  { path: "/formation/catholic-burial/planning-a-catholic-funeral", purpose: "Practical Catholic funeral planning guide with checklist and local-only planning notes tool" },
  { path: "/church-fathers", purpose: "Beginner-friendly Church Fathers guide, topic browser, reading plan, and trusted external research links" },
  { path: "/tools/heavenbound", purpose: "Launch portal for the external Heavenbound GPT spiritual companion" },
  { path: "/today", purpose: "Today in the Church dashboard" },
  { path: "/dashboard", purpose: "Alias for the liturgical living dashboard" },
  { path: "/liturgical-living", purpose: "Today in the Church, calendar, seasons, holy days, family practices" },
  { path: "/liturgical-living/calendar", purpose: "Liturgical month view with daily records" },
  { path: "/liturgical-living/seasons", purpose: "Season records, colors, focus, and practices" },
  { path: "/liturgical-living/advent", purpose: "Advent guide with hopeful preparation, confession, Scripture, and O Antiphon prayer" },
  { path: "/liturgical-living/advent/o-antiphons", purpose: "Guide to the O Antiphons prayed from December 17 to 23 as final preparation for Christmas" },
  { path: "/liturgical-living/christmas", purpose: "Christmas season guide and Advent-to-Christmas transition through the O Antiphons" },
  { path: "/liturgical-living/christmas/epiphany", purpose: "Epiphany guide for following the Magi, prayer, house blessing, and Christmas mission" },
  { path: "/liturgical-living/christmas/epiphany/house-blessing", purpose: "Family Epiphany home blessing guide and local-only printable planning tool" },
  { path: "/liturgical-living/holy-days", purpose: "Holy days and solemnities with local observance notes" },
  { path: "/liturgical-living/family", purpose: "Family prayer ideas and domestic Church practices" },
  { path: "/liturgical-living/settings", purpose: "Local calendar settings and Google Sheets schema" },
  { path: "/rule-of-life", purpose: "Daily Rule of Life overview" },
  { path: "/rule-of-life/builder", purpose: "LocalStorage rule of life builder" },
  { path: "/rule-of-life/my-rule", purpose: "Saved local rule display and export" },
  { path: "/rule-of-life/templates", purpose: "Rule of life templates" },
  { path: "/rule-of-life/examen", purpose: "Daily Examen guide" },
  { path: "/rule-of-life/print", purpose: "Printable rule of life view" },
  { path: "/pathways", purpose: "Spiritual Growth Pathways overview" },
  { path: "/pathways/start", purpose: "Choose a guided formation starting point" },
  { path: "/pathways/my-pathways", purpose: "LocalStorage pathway progress" },
  { path: "/pathways/recommended", purpose: "Local settings-based pathway recommendations" },
  { path: "/pathways/settings", purpose: "Local pathway recommendation settings" },
  { path: "/pathways/[slug]", purpose: "Spiritual growth pathway detail page" },
  { path: "/pathways/[slug]/steps/[stepSlug]", purpose: "Individual pathway step page" },
  { path: "/sacraments", purpose: "Sacrament Preparation Companion overview" },
  { path: "/sacraments/companion", purpose: "Browse sacrament preparation companions" },
  { path: "/sacraments/prepare", purpose: "LocalStorage sacrament preparation wizard" },
  { path: "/sacraments/my-preparation", purpose: "Saved local sacrament preparation progress" },
  { path: "/sacraments/print", purpose: "Printable/exportable preparation plan" },
  { path: "/sacraments/[slug]", purpose: "Specific sacrament preparation companion" },
  { path: "/confession", purpose: "Gentle Catholic Confession Guide hub with preparation, examination, prayers, and support" },
  { path: "/confession/examination", purpose: "Private local-only Guided Examination of Conscience" },
  { path: "/confession/examination/start", purpose: "Choose examination mode, state of life, and paths" },
  { path: "/confession/examination/ten-commandments", purpose: "Ten Commandments examination prompts" },
  { path: "/confession/examination/beatitudes", purpose: "Beatitudes examination prompts" },
  { path: "/confession/examination/state-of-life", purpose: "State of life, duties, prayer, sacramental life, and works of mercy prompts" },
  { path: "/confession/examination/virtues", purpose: "Virtues and vices examination prompts" },
  { path: "/confession/examination/review", purpose: "Review marked prompts and private local notes" },
  { path: "/confession/how-to-go", purpose: "Pastoral guide for going to confession" },
  { path: "/confession/sins", purpose: "Pastoral overview of sin, conscience, culpability, and conversion" },
  { path: "/confession/habitual-sin", purpose: "Gentle support for habitual sin, safeguards, confession, and contrary virtues" },
  { path: "/confession/resisting-temptation", purpose: "Practical Catholic guide for resisting temptation before consent" },
  { path: "/confession/predominant-fault", purpose: "Self-knowledge guide for naming a recurring fault and practicing a contrary virtue" },
  { path: "/confession/prayers", purpose: "Original prayers before and after confession" },
  { path: "/virtue-tracker", purpose: "Private local-only Virtue and Vice Tracker overview" },
  { path: "/virtue-tracker/dashboard", purpose: "Saved local check-ins and gentle dashboard summary" },
  { path: "/virtue-tracker/check-in", purpose: "Private local virtue and vice check-in flow" },
  { path: "/virtue-tracker/virtues", purpose: "Theological, cardinal, and contrary virtue library" },
  { path: "/virtue-tracker/vices", purpose: "Capital vice library with contrary virtues" },
  { path: "/virtue-tracker/patterns", purpose: "Private pattern summary without scores or streaks" },
  { path: "/virtue-tracker/confession-prep", purpose: "Private check-ins marked for confession preparation" },
  { path: "/virtue-tracker/settings", purpose: "Local settings, export, and delete controls" },
  { path: "/saints", purpose: "Catholic Saints Library, saint companion hub, virtues, patronages, and holiness formation" },
  { path: "/saints/finder", purpose: "Saint companion finder by need, virtue, and state of life" },
  { path: "/saints/calendar", purpose: "Saint feast day calendar" },
  { path: "/saints/patron-saints", purpose: "Patron saints directory by need, vocation, and state of life" },
  { path: "/saints/virtues", purpose: "Browse saints by virtue and weekly practices" },
  { path: "/saints/reading-plan", purpose: "Beginner saint reading path and 7-day challenge" },
  { path: "/saints/confirmation", purpose: "Confirmation saint helper and companion guide" },
  { path: "/saints/saint-of-the-day", purpose: "Saint of the day page with trusted sources" },
  { path: "/saints/companions", purpose: "Saved local saint companions" },
  { path: "/saints/patronage", purpose: "Saint patronage groups" },
  { path: "/saints/settings", purpose: "Local companion export/delete and Google Sheets saint schema" },
  { path: "/saints/[slug]", purpose: "Saint profile page" },
  { path: "/community", purpose: "Prayer requests, intention wall, prayer chain, events, groups, discussions" },
  { path: "/community/events", purpose: "Upcoming Daily Oratory prayer, formation, and local Catholic community events" },
  { path: "/community/events/[slug]", purpose: "Event detail with schedule, location, recurrence, preparation notes, and related resources" },
  { path: "/community/local-faith-groups", purpose: "Directory pattern for local Catholic prayer groups and formation circles" },
  { path: "/community/group-discussion-topics", purpose: "Prayerful Catholic discussion topics for families, parish groups, and formation teams" },
  { path: "/community/contact", purpose: "Community contact form placeholder for listings, events, and support questions" },
  { path: "/adoration", purpose: "Live Adoration Portal with featured, live, 24/7, and verified streams" },
  { path: "/adoration/live", purpose: "Filtered live and 24/7 Eucharistic Adoration streams" },
  { path: "/adoration/[slug]", purpose: "Stream detail prayer chapel with quiet mode, safe iframe, prayer panel, and reporting" },
  { path: "/adoration/prayers", purpose: "Adoration prayer panel for entering, silence, reparation, and leaving" },
  { path: "/adoration/submit-stream", purpose: "Local submit-stream review form plus Google Sheets schema and Apps Script plan" },
  { path: "/prayer-intentions", purpose: "Prayer intentions overview, privacy notes, and moderation-first ask for prayer flow" },
  { path: "/prayer-intentions/submit", purpose: "Local mock prayer intention submission form with privacy warnings" },
  { path: "/prayer-intentions/wall", purpose: "Legacy prayer wall path redirected to the main prayer intentions page" },
  { path: "/prayer-intentions/urgent", purpose: "Approved urgent public intentions with emergency disclaimer" },
  { path: "/prayer-intentions/thanksgivings", purpose: "Approved thanksgiving intentions" },
  { path: "/prayer-intentions/guidelines", purpose: "Moderation workflow, Google Sheets workflow, and Supabase-ready schema" },
  { path: "/prayer-intentions/[slug]", purpose: "Approved public prayer intention detail page" },
  { path: "/library", purpose: "All resources with search, category, tag, and season filters" },
  { path: "/library/[slug]", purpose: "Canonical resource detail page" },
  { path: "/about", purpose: "Mission, editorial posture, brand trust" },
  { path: "/mission", purpose: "How the Church prays, forms vocations, spreads the Gospel, and serves those in need" },
  { path: "/spiritual-warfare", purpose: "Catholic guidance on spiritual warfare, ordinary means of grace, discernment, and deliverance help" },
  { path: "/contact", purpose: "Corrections, contributions, and inquiries" },
] as const;
