import type { SectionPage } from "./types";

export const sectionPages: SectionPage[] = [
  {
    slug: "pray",
    title: "Pray",
    navLabel: "Pray",
    description: "Prayer Library, Catholic Devotions, Holy Rosary, Divine Mercy Chaplet, Live Adoration, Daily Rule of Life, and Confession Guide.",
    hero: "Begin with prayer and let the day become an offering.",
    primaryHref: "/library/morning-offering",
    primaryLabel: "Begin in prayer",
    categories: ["Prayer", "Rosary"],
    tags: ["Prayer Library", "Catholic Devotions", "Holy Rosary", "Divine Mercy Chaplet", "Live Adoration", "Daily Rule of Life", "Confession Guide"],
  },
  {
    slug: "reflect",
    title: "Reflect",
    navLabel: "Reflect",
    description: "Mass Readings Reflections, guided examination of conscience, and virtue review.",
    hero: "Carry one word from Scripture into the day.",
    primaryHref: "/reflections/mass-readings",
    primaryLabel: "Read Mass readings reflections",
    categories: ["Daily Reflection", "Scripture"],
    tags: ["Mass Readings", "Sunday Mass", "Examination of Conscience", "Virtue", "Scripture"],
  },
  {
    slug: "learn",
    title: "Learn",
    navLabel: "Learn",
    description: "Church Fathers, Catholic Devotions, Spiritual Growth Pathways, Sacraments, Saints, Scripture, Mass, Formation, and Body, Soul, and Spirit.",
    hero: "Grow in the Catholic faith with clarity and reverence.",
    primaryHref: "/pathways",
    primaryLabel: "Grow in virtue",
    categories: ["Sacraments", "Saints & Devotions", "Formation", "Scripture"],
    tags: ["Church Fathers", "Catholic Devotions", "Spiritual Growth", "Sacraments", "Saints", "Scripture", "Mass", "Formation", "Body, Soul, and Spirit"],
  },
  {
    slug: "liturgical-year",
    title: "Liturgical Year",
    navLabel: "Liturgical Year",
    description: "Today in the Church, liturgical living dashboard, calendar, seasons, holy days, and family liturgical living.",
    hero: "Let the Church teach you how to keep time.",
    primaryHref: "/liturgical-living",
    primaryLabel: "Live the liturgical year",
    categories: ["Liturgical Year"],
    tags: ["Today in the Church", "Calendar", "Seasons", "Holy Days", "Family Liturgical Living"],
  },
  {
    slug: "community",
    title: "Community",
    navLabel: "Community",
    description: "Prayer Intentions, Events, Local Faith Groups, and Group Discussion Topics.",
    hero: "Gather in prayer and go forth in mission.",
    primaryHref: "/community/events",
    primaryLabel: "View events",
    categories: ["Community"],
    tags: ["Prayer Intentions", "Events", "Local Faith Groups", "Discussion Topics"],
  },
];
