// @ts-nocheck
{
const { mkdirSync, readFileSync, writeFileSync } = require("node:fs");
const { join } = require("node:path");

const root = process.cwd();
const publicDir = join(root, "public");
const redirectsPath = join(publicDir, "_redirects");
const redirectsSourcePath = join(root, "src", "data", "redirects.ts");

const explicitRedirects = [
  {
    source: "https://www.dailyoratory.faith/*",
    destination: "https://dailyoratory.faith/:splat",
    permanent: true,
  },
  {
    source: "/reflections",
    destination: "/reflections/mass-readings",
    permanent: true,
  },
];

const redirects = [...explicitRedirects, ...readImplementedRedirects()]
  .filter((redirect) => redirect.source !== redirect.destination)
  .map((redirect) => {
    const status = redirect.permanent ? "301" : "302";
    return `${redirect.source} ${redirect.destination} ${status}`;
  });

const content = [
  "# Generated by scripts/write-cloudflare-redirects.ts.",
  "# Cloudflare Pages reads this file from the static export output.",
  ...Array.from(new Set(redirects)),
  "",
].join("\n");

mkdirSync(publicDir, { recursive: true });
writeFileSync(redirectsPath, content, "utf8");

console.log(`Wrote ${redirects.length} Cloudflare redirect rules to public/_redirects.`);

function readImplementedRedirects() {
  const source = readFileSync(redirectsSourcePath, "utf8");
  const ruleBlocks = source.match(/\{[\s\S]*?source:\s*"[^"]+"[\s\S]*?notes:\s*"[^"]*"[\s\S]*?\}/g) ?? [];

  return ruleBlocks
    .map((block) => {
      const sourceMatch = block.match(/source:\s*"([^"]+)"/);
      const destinationMatch = block.match(/destination:\s*"([^"]+)"/);
      const permanentMatch = block.match(/permanent:\s*(true|false)/);
      const statusMatch = block.match(/status:\s*"([^"]+)"/);

      if (!sourceMatch?.[1] || !destinationMatch?.[1] || !permanentMatch?.[1]) return null;
      if (statusMatch?.[1] !== "implemented") return null;

      return {
        source: sourceMatch[1],
        destination: destinationMatch[1],
        permanent: permanentMatch[1] === "true",
      };
    })
    .filter(Boolean);
}
}
